// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/olshmore/ytter/internal/worker (interfaces: TaskDistributor)

// Package mockwk is a generated GoMock package.
package mockwk

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	asynq "github.com/hibiken/asynq"
	worker "github.com/olshmore/ytter/internal/worker"
)

// MockTaskDistributor is a mock of TaskDistributor interface.
type MockTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistributorMockRecorder
}

// MockTaskDistributorMockRecorder is the mock recorder for MockTaskDistributor.
type MockTaskDistributorMockRecorder struct {
	mock *MockTaskDistributor
}

// NewMockTaskDistributor creates a new mock instance.
func NewMockTaskDistributor(ctrl *gomock.Controller) *MockTaskDistributor {
	mock := &MockTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistributor) EXPECT() *MockTaskDistributorMockRecorder {
	return m.recorder
}

// DistributeTaskSendVerificationEmail mocks base method.
func (m *MockTaskDistributor) DistributeTaskSendVerificationEmail(arg0 context.Context, arg1 *worker.PayloadSendVerificationEmail, arg2 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskSendVerificationEmail", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskSendVerificationEmail indicates an expected call of DistributeTaskSendVerificationEmail.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskSendVerificationEmail(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskSendVerificationEmail", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskSendVerificationEmail), varargs...)
}

// DistributeTaskSendBookingEmail mocks base method.
func (m *MockTaskDistributor) DistributeTaskSendBookingEmail(arg0 context.Context, arg1 *worker.PayloadSendBookingEmail, arg2 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskSendBookingEmail", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskSendBookingEmail indicates an expected call of DistributeTaskSendBookingEmail.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskSendBookingEmail(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskSendBookingEmail", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskSendBookingEmail), varargs...)
}

// DistributeTaskSendBookingReminderEmail mocks base method.
func (m *MockTaskDistributor) DistributeTaskSendBookingReminderEmail(arg0 context.Context, arg1 *worker.PayloadSendBookingReminderEmail, arg2 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskSendBookingReminderEmail", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskSendBookingReminderEmail indicates an expected call of DistributeTaskSendBookingReminderEmail.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskSendBookingReminderEmail(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskSendBookingReminderEmail", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskSendBookingReminderEmail), varargs...)
}
