// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: booking.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearBookingNoShow = `-- name: ClearBookingNoShow :one
UPDATE bookings
SET
  status = 'confirmed',
  updated_at = now()
WHERE id = $1
  AND status = 'no_show'
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
RETURNING id, location_id, slot_id, status, guest_name, guest_email, guest_phone, guest_notes, client_username, booked_at, cancelled_at, cancel_reason, cancel_token_hash, created_at, updated_at, deleted_at
`

func (q *Queries) ClearBookingNoShow(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, clearBookingNoShow, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.SlotID,
		&i.Status,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.GuestNotes,
		&i.ClientUsername,
		&i.BookedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CancelTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const confirmBooking = `-- name: ConfirmBooking :one
UPDATE bookings
SET
  status = 'confirmed',
  updated_at = now()
WHERE id = $1
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
RETURNING id, location_id, slot_id, status, guest_name, guest_email, guest_phone, guest_notes, client_username, booked_at, cancelled_at, cancel_reason, cancel_token_hash, created_at, updated_at, deleted_at
`

func (q *Queries) ConfirmBooking(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, confirmBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.SlotID,
		&i.Status,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.GuestNotes,
		&i.ClientUsername,
		&i.BookedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CancelTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countActiveWaitlistEntriesForSlot = `-- name: CountActiveWaitlistEntriesForSlot :one
SELECT COUNT(*)::int4 AS count
FROM waitlist_entries
WHERE slot_id = $1
  AND status = 'active'
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
`

func (q *Queries) CountActiveWaitlistEntriesForSlot(ctx context.Context, slotID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveWaitlistEntriesForSlot, slotID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countHostBookingsByLocation = `-- name: CountHostBookingsByLocation :one
WITH unified AS (
  SELECT
    b.status,
    s.start_at,
    l.timezone
  FROM bookings b
  JOIN appointment_slots s ON s.id = b.slot_id
  JOIN locations l ON l.id = b.location_id
  WHERE b.location_id = $1
    AND b.deleted_at = '0001-01-01 00:00:00Z'::timestamptz

  UNION ALL

  SELECT
    'pending'::varchar AS status,
    s.start_at,
    l.timezone
  FROM waitlist_entries w
  JOIN appointment_slots s ON s.id = w.slot_id
  JOIN locations l ON l.id = w.location_id
  WHERE w.location_id = $1
    AND w.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
    AND w.status = 'active'
)
SELECT COUNT(*)::int4 AS count
FROM unified u
WHERE (
    COALESCE($2::text, '') = ''
    OR u.status = $2
  )
  AND (
    COALESCE($3::text, '') = ''
    OR (u.start_at AT TIME ZONE u.timezone)::date >= $3::date
  )
  AND (
    COALESCE($4::text, '') = ''
    OR (u.start_at AT TIME ZONE u.timezone)::date <= $4::date
  )
`

type CountHostBookingsByLocationParams struct {
	LocationID   uuid.UUID   `json:"location_id"`
	FilterStatus pgtype.Text `json:"filter_status"`
	FromDate     pgtype.Text `json:"from_date"`
	ToDate       pgtype.Text `json:"to_date"`
}

func (q *Queries) CountHostBookingsByLocation(ctx context.Context, arg CountHostBookingsByLocationParams) (int32, error) {
	row := q.db.QueryRow(ctx, countHostBookingsByLocation,
		arg.LocationID,
		arg.FilterStatus,
		arg.FromDate,
		arg.ToDate,
	)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countHostServicesByLocation = `-- name: CountHostServicesByLocation :one
SELECT COUNT(*)::int4 AS count
FROM services s
WHERE s.location_id = $1
  AND s.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND (
    $2::bool IS NULL
    OR s.is_active = $2
  )
`

type CountHostServicesByLocationParams struct {
	LocationID     uuid.UUID   `json:"location_id"`
	FilterIsActive pgtype.Bool `json:"filter_is_active"`
}

func (q *Queries) CountHostServicesByLocation(ctx context.Context, arg CountHostServicesByLocationParams) (int32, error) {
	row := q.db.QueryRow(ctx, countHostServicesByLocation, arg.LocationID, arg.FilterIsActive)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countHostSlotsByLocation = `-- name: CountHostSlotsByLocation :one
SELECT COUNT(*)::int4 AS count
FROM appointment_slots s
WHERE s.location_id = $1
  AND s.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND (
    COALESCE($2::text, '') = ''
    OR s.status = $2
  )
  AND (
    COALESCE($3::text, '') = ''
    OR s.start_at::date >= $3::date
  )
  AND (
    COALESCE($4::text, '') = ''
    OR s.start_at::date <= $4::date
  )
  AND (
    COALESCE($5::uuid, NULL::uuid) IS NULL
    OR s.service_id = $5
  )
  AND (
    COALESCE($6::uuid, NULL::uuid) IS NULL
    OR s.practitioner_id = $6
  )
  AND (
    COALESCE($7::uuid, NULL::uuid) IS NULL
    OR s.room_id = $7
  )
`

type CountHostSlotsByLocationParams struct {
	LocationID           uuid.UUID   `json:"location_id"`
	FilterStatus         pgtype.Text `json:"filter_status"`
	FromDate             pgtype.Text `json:"from_date"`
	ToDate               pgtype.Text `json:"to_date"`
	FilterServiceID      pgtype.UUID `json:"filter_service_id"`
	FilterPractitionerID pgtype.UUID `json:"filter_practitioner_id"`
	FilterRoomID         pgtype.UUID `json:"filter_room_id"`
}

func (q *Queries) CountHostSlotsByLocation(ctx context.Context, arg CountHostSlotsByLocationParams) (int32, error) {
	row := q.db.QueryRow(ctx, countHostSlotsByLocation,
		arg.LocationID,
		arg.FilterStatus,
		arg.FromDate,
		arg.ToDate,
		arg.FilterServiceID,
		arg.FilterPractitionerID,
		arg.FilterRoomID,
	)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countMyBookings = `-- name: CountMyBookings :one
SELECT COUNT(*)::int4 AS count
FROM bookings b
JOIN appointment_slots s ON s.id = b.slot_id
JOIN locations l ON l.id = b.location_id
WHERE (
    b.client_username = $1
    OR (
    COALESCE($2::text, '') <> ''
    AND lower(b.guest_email) = lower($2)
    )
  )
  AND b.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND (
    COALESCE($3::text, '') = ''
    OR b.status = $3
  )
  AND (
    COALESCE($4::text, '') = ''
    OR (s.start_at AT TIME ZONE l.timezone)::date >= $4::date
  )
  AND (
    COALESCE($5::text, '') = ''
    OR (s.start_at AT TIME ZONE l.timezone)::date <= $5::date
  )
`

type CountMyBookingsParams struct {
	ClientUsername   pgtype.Text `json:"client_username"`
	FilterGuestEmail pgtype.Text `json:"filter_guest_email"`
	FilterStatus     pgtype.Text `json:"filter_status"`
	FromDate         pgtype.Text `json:"from_date"`
	ToDate           pgtype.Text `json:"to_date"`
}

func (q *Queries) CountMyBookings(ctx context.Context, arg CountMyBookingsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countMyBookings,
		arg.ClientUsername,
		arg.FilterGuestEmail,
		arg.FilterStatus,
		arg.FromDate,
		arg.ToDate,
	)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
  location_id,
  slot_id,
  status,
  guest_name,
  guest_email,
  guest_phone,
  guest_notes,
  cancel_token_hash,
  client_username
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, location_id, slot_id, status, guest_name, guest_email, guest_phone, guest_notes, client_username, booked_at, cancelled_at, cancel_reason, cancel_token_hash, created_at, updated_at, deleted_at
`

type CreateBookingParams struct {
	LocationID      uuid.UUID   `json:"location_id"`
	SlotID          uuid.UUID   `json:"slot_id"`
	Status          string      `json:"status"`
	GuestName       string      `json:"guest_name"`
	GuestEmail      string      `json:"guest_email"`
	GuestPhone      pgtype.Text `json:"guest_phone"`
	GuestNotes      pgtype.Text `json:"guest_notes"`
	CancelTokenHash string      `json:"cancel_token_hash"`
	ClientUsername  pgtype.Text `json:"client_username"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.LocationID,
		arg.SlotID,
		arg.Status,
		arg.GuestName,
		arg.GuestEmail,
		arg.GuestPhone,
		arg.GuestNotes,
		arg.CancelTokenHash,
		arg.ClientUsername,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.SlotID,
		&i.Status,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.GuestNotes,
		&i.ClientUsername,
		&i.BookedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CancelTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createHostLocationService = `-- name: CreateHostLocationService :one
INSERT INTO services (
  location_id,
  name,
  description,
  duration_minutes,
  price_minor_units,
  currency,
  is_active,
  cancellation_min_hours_before_start
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, location_id, name, description, duration_minutes, price_minor_units, currency, is_active, cancellation_min_hours_before_start, created_at, updated_at, deleted_at
`

type CreateHostLocationServiceParams struct {
	LocationID                      uuid.UUID   `json:"location_id"`
	Name                            string      `json:"name"`
	Description                     string      `json:"description"`
	DurationMinutes                 int32       `json:"duration_minutes"`
	PriceMinorUnits                 int64       `json:"price_minor_units"`
	Currency                        string      `json:"currency"`
	IsActive                        bool        `json:"is_active"`
	CancellationMinHoursBeforeStart pgtype.Int4 `json:"cancellation_min_hours_before_start"`
}

func (q *Queries) CreateHostLocationService(ctx context.Context, arg CreateHostLocationServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createHostLocationService,
		arg.LocationID,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.PriceMinorUnits,
		arg.Currency,
		arg.IsActive,
		arg.CancellationMinHoursBeforeStart,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.PriceMinorUnits,
		&i.Currency,
		&i.IsActive,
		&i.CancellationMinHoursBeforeStart,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createHostLocationSlot = `-- name: CreateHostLocationSlot :one
INSERT INTO appointment_slots (
  location_id,
  service_id,
  practitioner_id,
  room_id,
  start_at,
  end_at,
  capacity,
  status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, location_id, service_id, practitioner_id, room_id, start_at, end_at, capacity, booked_count, status, created_at, updated_at, deleted_at
`

type CreateHostLocationSlotParams struct {
	LocationID     uuid.UUID   `json:"location_id"`
	ServiceID      uuid.UUID   `json:"service_id"`
	PractitionerID pgtype.UUID `json:"practitioner_id"`
	RoomID         pgtype.UUID `json:"room_id"`
	StartAt        time.Time   `json:"start_at"`
	EndAt          time.Time   `json:"end_at"`
	Capacity       int32       `json:"capacity"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateHostLocationSlot(ctx context.Context, arg CreateHostLocationSlotParams) (AppointmentSlot, error) {
	row := q.db.QueryRow(ctx, createHostLocationSlot,
		arg.LocationID,
		arg.ServiceID,
		arg.PractitionerID,
		arg.RoomID,
		arg.StartAt,
		arg.EndAt,
		arg.Capacity,
		arg.Status,
	)
	var i AppointmentSlot
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.ServiceID,
		&i.PractitionerID,
		&i.RoomID,
		&i.StartAt,
		&i.EndAt,
		&i.Capacity,
		&i.BookedCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (
  owner_username,
  name,
  slug,
  timezone,
  is_active
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, owner_username, name, slug, timezone, is_active, booking_requires_host_approval, cancellation_min_hours_before_start, created_at, updated_at, deleted_at, logo_url, primary_color, accent_color, font_family, background_color
`

type CreateLocationParams struct {
	OwnerUsername string `json:"owner_username"`
	Name          string `json:"name"`
	Slug          string `json:"slug"`
	Timezone      string `json:"timezone"`
	IsActive      bool   `json:"is_active"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.OwnerUsername,
		arg.Name,
		arg.Slug,
		arg.Timezone,
		arg.IsActive,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OwnerUsername,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.IsActive,
		&i.BookingRequiresHostApproval,
		&i.CancellationMinHoursBeforeStart,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.FontFamily,
		&i.BackgroundColor,
	)
	return i, err
}

const createWaitlistEntry = `-- name: CreateWaitlistEntry :one
INSERT INTO waitlist_entries (
  location_id,
  service_id,
  slot_id,
  guest_name,
  guest_email,
  guest_phone,
  practitioner_id,
  preferred_date,
  status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, 'active'
)
RETURNING id, location_id, service_id, slot_id, guest_name, guest_email, guest_phone, practitioner_id, preferred_date, status, offer_token_hash, offer_expires_at, created_at, updated_at, deleted_at
`

type CreateWaitlistEntryParams struct {
	LocationID     uuid.UUID   `json:"location_id"`
	ServiceID      uuid.UUID   `json:"service_id"`
	SlotID         uuid.UUID   `json:"slot_id"`
	GuestName      string      `json:"guest_name"`
	GuestEmail     string      `json:"guest_email"`
	GuestPhone     pgtype.Text `json:"guest_phone"`
	PractitionerID pgtype.UUID `json:"practitioner_id"`
	PreferredDate  pgtype.Date `json:"preferred_date"`
}

func (q *Queries) CreateWaitlistEntry(ctx context.Context, arg CreateWaitlistEntryParams) (WaitlistEntry, error) {
	row := q.db.QueryRow(ctx, createWaitlistEntry,
		arg.LocationID,
		arg.ServiceID,
		arg.SlotID,
		arg.GuestName,
		arg.GuestEmail,
		arg.GuestPhone,
		arg.PractitionerID,
		arg.PreferredDate,
	)
	var i WaitlistEntry
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.ServiceID,
		&i.SlotID,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.PractitionerID,
		&i.PreferredDate,
		&i.Status,
		&i.OfferTokenHash,
		&i.OfferExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveWaitlistEntryByIdentity = `-- name: GetActiveWaitlistEntryByIdentity :one
SELECT id, location_id, service_id, slot_id, guest_name, guest_email, guest_phone, practitioner_id, preferred_date, status, offer_token_hash, offer_expires_at, created_at, updated_at, deleted_at
FROM waitlist_entries
WHERE location_id = $1
  AND service_id = $2
  AND slot_id = $3
  AND lower(guest_email) = lower($4)
  AND status = 'active'
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
LIMIT 1
`

type GetActiveWaitlistEntryByIdentityParams struct {
	LocationID uuid.UUID `json:"location_id"`
	ServiceID  uuid.UUID `json:"service_id"`
	SlotID     uuid.UUID `json:"slot_id"`
	GuestEmail string    `json:"guest_email"`
}

func (q *Queries) GetActiveWaitlistEntryByIdentity(ctx context.Context, arg GetActiveWaitlistEntryByIdentityParams) (WaitlistEntry, error) {
	row := q.db.QueryRow(ctx, getActiveWaitlistEntryByIdentity,
		arg.LocationID,
		arg.ServiceID,
		arg.SlotID,
		arg.GuestEmail,
	)
	var i WaitlistEntry
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.ServiceID,
		&i.SlotID,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.PractitionerID,
		&i.PreferredDate,
		&i.Status,
		&i.OfferTokenHash,
		&i.OfferExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, location_id, slot_id, status, guest_name, guest_email, guest_phone, guest_notes, client_username, booked_at, cancelled_at, cancel_reason, cancel_token_hash, created_at, updated_at, deleted_at FROM bookings
WHERE id = $1
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
LIMIT 1
`

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.SlotID,
		&i.Status,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.GuestNotes,
		&i.ClientUsername,
		&i.BookedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CancelTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBookingForCancelByIDForUpdate = `-- name: GetBookingForCancelByIDForUpdate :one
SELECT
  b.id, b.location_id, b.slot_id, b.status, b.guest_name, b.guest_email, b.guest_phone, b.guest_notes, b.client_username, b.booked_at, b.cancelled_at, b.cancel_reason, b.cancel_token_hash, b.created_at, b.updated_at, b.deleted_at,
  s.start_at,
  s.booked_count,
  s.capacity,
  sv.cancellation_min_hours_before_start AS service_cancellation_min_hours_before_start,
  l.cancellation_min_hours_before_start AS location_cancellation_min_hours_before_start
FROM bookings b
JOIN appointment_slots s ON s.id = b.slot_id
JOIN services sv ON sv.id = s.service_id
JOIN locations l ON l.id = b.location_id
WHERE b.id = $1
  AND b.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
FOR UPDATE
`

type GetBookingForCancelByIDForUpdateRow struct {
	ID                                      uuid.UUID          `json:"id"`
	LocationID                              uuid.UUID          `json:"location_id"`
	SlotID                                  uuid.UUID          `json:"slot_id"`
	Status                                  string             `json:"status"`
	GuestName                               string             `json:"guest_name"`
	GuestEmail                              string             `json:"guest_email"`
	GuestPhone                              pgtype.Text        `json:"guest_phone"`
	GuestNotes                              pgtype.Text        `json:"guest_notes"`
	ClientUsername                          pgtype.Text        `json:"client_username"`
	BookedAt                                time.Time          `json:"booked_at"`
	CancelledAt                             pgtype.Timestamptz `json:"cancelled_at"`
	CancelReason                            pgtype.Text        `json:"cancel_reason"`
	CancelTokenHash                         string             `json:"cancel_token_hash"`
	CreatedAt                               time.Time          `json:"created_at"`
	UpdatedAt                               time.Time          `json:"updated_at"`
	DeletedAt                               time.Time          `json:"deleted_at"`
	StartAt                                 time.Time          `json:"start_at"`
	BookedCount                             int32              `json:"booked_count"`
	Capacity                                int32              `json:"capacity"`
	ServiceCancellationMinHoursBeforeStart  pgtype.Int4        `json:"service_cancellation_min_hours_before_start"`
	LocationCancellationMinHoursBeforeStart pgtype.Int4        `json:"location_cancellation_min_hours_before_start"`
}

func (q *Queries) GetBookingForCancelByIDForUpdate(ctx context.Context, id uuid.UUID) (GetBookingForCancelByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getBookingForCancelByIDForUpdate, id)
	var i GetBookingForCancelByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.SlotID,
		&i.Status,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.GuestNotes,
		&i.ClientUsername,
		&i.BookedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CancelTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.StartAt,
		&i.BookedCount,
		&i.Capacity,
		&i.ServiceCancellationMinHoursBeforeStart,
		&i.LocationCancellationMinHoursBeforeStart,
	)
	return i, err
}

const getBookingForHostOpByIDForUpdate = `-- name: GetBookingForHostOpByIDForUpdate :one
SELECT
  b.id,
  b.location_id,
  b.slot_id,
  b.status,
  b.guest_name,
  b.guest_email,
  b.guest_phone,
  b.guest_notes,
  b.client_username,
  b.booked_at,
  b.cancelled_at,
  b.cancel_reason,
  b.cancel_token_hash,
  b.created_at,
  b.updated_at,
  b.deleted_at,
  s.start_at,
  s.booked_count,
  s.capacity,
  l.owner_username
FROM bookings b
JOIN appointment_slots s ON s.id = b.slot_id
JOIN locations l ON l.id = b.location_id
WHERE b.id = $1
  AND b.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
FOR UPDATE
`

type GetBookingForHostOpByIDForUpdateRow struct {
	ID              uuid.UUID          `json:"id"`
	LocationID      uuid.UUID          `json:"location_id"`
	SlotID          uuid.UUID          `json:"slot_id"`
	Status          string             `json:"status"`
	GuestName       string             `json:"guest_name"`
	GuestEmail      string             `json:"guest_email"`
	GuestPhone      pgtype.Text        `json:"guest_phone"`
	GuestNotes      pgtype.Text        `json:"guest_notes"`
	ClientUsername  pgtype.Text        `json:"client_username"`
	BookedAt        time.Time          `json:"booked_at"`
	CancelledAt     pgtype.Timestamptz `json:"cancelled_at"`
	CancelReason    pgtype.Text        `json:"cancel_reason"`
	CancelTokenHash string             `json:"cancel_token_hash"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       time.Time          `json:"deleted_at"`
	StartAt         time.Time          `json:"start_at"`
	BookedCount     int32              `json:"booked_count"`
	Capacity        int32              `json:"capacity"`
	OwnerUsername   string             `json:"owner_username"`
}

func (q *Queries) GetBookingForHostOpByIDForUpdate(ctx context.Context, id uuid.UUID) (GetBookingForHostOpByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getBookingForHostOpByIDForUpdate, id)
	var i GetBookingForHostOpByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.SlotID,
		&i.Status,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.GuestNotes,
		&i.ClientUsername,
		&i.BookedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CancelTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.StartAt,
		&i.BookedCount,
		&i.Capacity,
		&i.OwnerUsername,
	)
	return i, err
}

const getHostBookingAnalyticsSummary = `-- name: GetHostBookingAnalyticsSummary :one
WITH filtered AS (
  SELECT
    b.status,
    b.booked_at,
    s.start_at
  FROM bookings b
  JOIN appointment_slots s ON s.id = b.slot_id
  JOIN locations l ON l.id = b.location_id
  WHERE b.location_id = $1
    AND b.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
    AND s.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
    AND (
      COALESCE($2::text, '') = ''
      OR (s.start_at AT TIME ZONE l.timezone)::date >= $2::date
    )
    AND (
      COALESCE($3::text, '') = ''
      OR (s.start_at AT TIME ZONE l.timezone)::date <= $3::date
    )
)
SELECT
  COUNT(*)::int4 AS total_count,
  COUNT(*) FILTER (WHERE status IN ('confirmed', 'completed'))::int4 AS filled_count,
  COUNT(*) FILTER (WHERE status = 'cancelled')::int4 AS cancelled_count,
  COUNT(*) FILTER (WHERE status = 'pending')::int4 AS pending_count,
  COUNT(*) FILTER (WHERE status = 'no_show')::int4 AS no_show_count,
  COALESCE(
    AVG(
      CASE
        WHEN status = 'pending' THEN EXTRACT(EPOCH FROM (now() - booked_at)) / 60.0
        ELSE NULL
      END
    )::float8,
    0
  ) AS pending_approval_avg_minutes
FROM filtered
`

type GetHostBookingAnalyticsSummaryParams struct {
	LocationID uuid.UUID   `json:"location_id"`
	FromDate   pgtype.Text `json:"from_date"`
	ToDate     pgtype.Text `json:"to_date"`
}

type GetHostBookingAnalyticsSummaryRow struct {
	TotalCount                int32       `json:"total_count"`
	FilledCount               int32       `json:"filled_count"`
	CancelledCount            int32       `json:"cancelled_count"`
	PendingCount              int32       `json:"pending_count"`
	NoShowCount               int32       `json:"no_show_count"`
	PendingApprovalAvgMinutes interface{} `json:"pending_approval_avg_minutes"`
}

func (q *Queries) GetHostBookingAnalyticsSummary(ctx context.Context, arg GetHostBookingAnalyticsSummaryParams) (GetHostBookingAnalyticsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getHostBookingAnalyticsSummary, arg.LocationID, arg.FromDate, arg.ToDate)
	var i GetHostBookingAnalyticsSummaryRow
	err := row.Scan(
		&i.TotalCount,
		&i.FilledCount,
		&i.CancelledCount,
		&i.PendingCount,
		&i.NoShowCount,
		&i.PendingApprovalAvgMinutes,
	)
	return i, err
}

const getHostServiceByID = `-- name: GetHostServiceByID :one
SELECT id, location_id, name, description, duration_minutes, price_minor_units, currency, is_active, cancellation_min_hours_before_start, created_at, updated_at, deleted_at FROM services
WHERE id = $1
  AND location_id = $2
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
LIMIT 1
`

type GetHostServiceByIDParams struct {
	ID         uuid.UUID `json:"id"`
	LocationID uuid.UUID `json:"location_id"`
}

func (q *Queries) GetHostServiceByID(ctx context.Context, arg GetHostServiceByIDParams) (Service, error) {
	row := q.db.QueryRow(ctx, getHostServiceByID, arg.ID, arg.LocationID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.PriceMinorUnits,
		&i.Currency,
		&i.IsActive,
		&i.CancellationMinHoursBeforeStart,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getHostSlotByID = `-- name: GetHostSlotByID :one
SELECT id, location_id, service_id, practitioner_id, room_id, start_at, end_at, capacity, booked_count, status, created_at, updated_at, deleted_at FROM appointment_slots
WHERE id = $1
  AND location_id = $2
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
LIMIT 1
`

type GetHostSlotByIDParams struct {
	ID         uuid.UUID `json:"id"`
	LocationID uuid.UUID `json:"location_id"`
}

func (q *Queries) GetHostSlotByID(ctx context.Context, arg GetHostSlotByIDParams) (AppointmentSlot, error) {
	row := q.db.QueryRow(ctx, getHostSlotByID, arg.ID, arg.LocationID)
	var i AppointmentSlot
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.ServiceID,
		&i.PractitionerID,
		&i.RoomID,
		&i.StartAt,
		&i.EndAt,
		&i.Capacity,
		&i.BookedCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, owner_username, name, slug, timezone, is_active, booking_requires_host_approval, cancellation_min_hours_before_start, created_at, updated_at, deleted_at, logo_url, primary_color, accent_color, font_family, background_color FROM locations
WHERE id = $1
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
LIMIT 1
`

func (q *Queries) GetLocationByID(ctx context.Context, id uuid.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OwnerUsername,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.IsActive,
		&i.BookingRequiresHostApproval,
		&i.CancellationMinHoursBeforeStart,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.FontFamily,
		&i.BackgroundColor,
	)
	return i, err
}

const getLocationBySlug = `-- name: GetLocationBySlug :one
SELECT id, owner_username, name, slug, timezone, is_active, booking_requires_host_approval, cancellation_min_hours_before_start, created_at, updated_at, deleted_at, logo_url, primary_color, accent_color, font_family, background_color FROM locations
WHERE slug = $1
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
LIMIT 1
`

func (q *Queries) GetLocationBySlug(ctx context.Context, slug string) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationBySlug, slug)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OwnerUsername,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.IsActive,
		&i.BookingRequiresHostApproval,
		&i.CancellationMinHoursBeforeStart,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.FontFamily,
		&i.BackgroundColor,
	)
	return i, err
}

const getPractitionerByID = `-- name: GetPractitionerByID :one
SELECT id, location_id, name, display_name, is_active, created_at, updated_at, deleted_at FROM practitioners
WHERE id = $1
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
LIMIT 1
`

func (q *Queries) GetPractitionerByID(ctx context.Context, id uuid.UUID) (Practitioner, error) {
	row := q.db.QueryRow(ctx, getPractitionerByID, id)
	var i Practitioner
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRebookContextByBookingID = `-- name: GetRebookContextByBookingID :one
SELECT
  b.id AS booking_id,
  b.client_username,
  b.guest_email,
  l.id AS location_id,
  l.slug AS location_slug,
  l.name AS location_name,
  sv.id AS service_id,
  sv.name AS service_name,
  s.practitioner_id,
  l.is_active AS location_is_active,
  sv.is_active AS service_is_active
FROM bookings b
JOIN locations l ON l.id = b.location_id
JOIN appointment_slots s ON s.id = b.slot_id
JOIN services sv ON sv.id = s.service_id
WHERE b.id = $1
  AND b.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND l.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND s.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND sv.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
LIMIT 1
`

type GetRebookContextByBookingIDRow struct {
	BookingID        uuid.UUID   `json:"booking_id"`
	ClientUsername   pgtype.Text `json:"client_username"`
	GuestEmail       string      `json:"guest_email"`
	LocationID       uuid.UUID   `json:"location_id"`
	LocationSlug     string      `json:"location_slug"`
	LocationName     string      `json:"location_name"`
	ServiceID        uuid.UUID   `json:"service_id"`
	ServiceName      string      `json:"service_name"`
	PractitionerID   pgtype.UUID `json:"practitioner_id"`
	LocationIsActive bool        `json:"location_is_active"`
	ServiceIsActive  bool        `json:"service_is_active"`
}

func (q *Queries) GetRebookContextByBookingID(ctx context.Context, id uuid.UUID) (GetRebookContextByBookingIDRow, error) {
	row := q.db.QueryRow(ctx, getRebookContextByBookingID, id)
	var i GetRebookContextByBookingIDRow
	err := row.Scan(
		&i.BookingID,
		&i.ClientUsername,
		&i.GuestEmail,
		&i.LocationID,
		&i.LocationSlug,
		&i.LocationName,
		&i.ServiceID,
		&i.ServiceName,
		&i.PractitionerID,
		&i.LocationIsActive,
		&i.ServiceIsActive,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, location_id, name, is_active, created_at, updated_at, deleted_at FROM rooms
WHERE id = $1
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
LIMIT 1
`

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, location_id, name, description, duration_minutes, price_minor_units, currency, is_active, cancellation_min_hours_before_start, created_at, updated_at, deleted_at FROM services
WHERE id = $1
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
LIMIT 1
`

func (q *Queries) GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.PriceMinorUnits,
		&i.Currency,
		&i.IsActive,
		&i.CancellationMinHoursBeforeStart,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSlotForUpdate = `-- name: GetSlotForUpdate :one
SELECT id, location_id, service_id, practitioner_id, room_id, start_at, end_at, capacity, booked_count, status, created_at, updated_at, deleted_at FROM appointment_slots
WHERE id = $1
  AND location_id = $2
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
FOR UPDATE
`

type GetSlotForUpdateParams struct {
	ID         uuid.UUID `json:"id"`
	LocationID uuid.UUID `json:"location_id"`
}

func (q *Queries) GetSlotForUpdate(ctx context.Context, arg GetSlotForUpdateParams) (AppointmentSlot, error) {
	row := q.db.QueryRow(ctx, getSlotForUpdate, arg.ID, arg.LocationID)
	var i AppointmentSlot
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.ServiceID,
		&i.PractitionerID,
		&i.RoomID,
		&i.StartAt,
		&i.EndAt,
		&i.Capacity,
		&i.BookedCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllHostLocations = `-- name: ListAllHostLocations :many
SELECT
  id,
  owner_username,
  slug,
  name,
  timezone,
  is_active,
  booking_requires_host_approval,
  COALESCE(cancellation_min_hours_before_start, 24)::int AS effective_cancellation_min_hours_before_start,
  logo_url,
  primary_color,
  accent_color,
  background_color,
  font_family
FROM locations
WHERE deleted_at = '0001-01-01 00:00:00Z'::timestamptz
ORDER BY name ASC
`

type ListAllHostLocationsRow struct {
	ID                                       uuid.UUID   `json:"id"`
	OwnerUsername                            string      `json:"owner_username"`
	Slug                                     string      `json:"slug"`
	Name                                     string      `json:"name"`
	Timezone                                 string      `json:"timezone"`
	IsActive                                 bool        `json:"is_active"`
	BookingRequiresHostApproval              bool        `json:"booking_requires_host_approval"`
	EffectiveCancellationMinHoursBeforeStart int32       `json:"effective_cancellation_min_hours_before_start"`
	LogoUrl                                  pgtype.Text `json:"logo_url"`
	PrimaryColor                             pgtype.Text `json:"primary_color"`
	AccentColor                              pgtype.Text `json:"accent_color"`
	BackgroundColor                          pgtype.Text `json:"background_color"`
	FontFamily                               pgtype.Text `json:"font_family"`
}

func (q *Queries) ListAllHostLocations(ctx context.Context) ([]ListAllHostLocationsRow, error) {
	rows, err := q.db.Query(ctx, listAllHostLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllHostLocationsRow{}
	for rows.Next() {
		var i ListAllHostLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUsername,
			&i.Slug,
			&i.Name,
			&i.Timezone,
			&i.IsActive,
			&i.BookingRequiresHostApproval,
			&i.EffectiveCancellationMinHoursBeforeStart,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.AccentColor,
			&i.BackgroundColor,
			&i.FontFamily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostBookingsByLocation = `-- name: ListHostBookingsByLocation :many
WITH unified AS (
  SELECT
    b.id AS booking_id,
    b.status,
    b.booked_at,
    b.guest_name,
    b.guest_email,
    b.guest_phone,
    b.cancel_reason,
    l.id AS location_id,
    l.slug AS location_slug,
    l.name AS location_name,
    s.id AS slot_id,
    sv.name AS service_name,
    COALESCE(p.display_name, '') AS practitioner_name,
    COALESCE(r.name, '') AS room_name,
    s.start_at,
    s.end_at,
    FALSE AS is_waitlist
  FROM bookings b
  JOIN appointment_slots s ON s.id = b.slot_id
  JOIN services sv ON sv.id = s.service_id
  LEFT JOIN practitioners p ON p.id = s.practitioner_id
  LEFT JOIN rooms r ON r.id = s.room_id
  JOIN locations l ON l.id = b.location_id
  WHERE b.location_id = $1
    AND b.deleted_at = '0001-01-01 00:00:00Z'::timestamptz

  UNION ALL

  SELECT
    w.id AS booking_id,
    'pending'::varchar AS status,
    w.created_at AS booked_at,
    w.guest_name,
    w.guest_email,
    w.guest_phone,
    NULL::varchar AS cancel_reason,
    l.id AS location_id,
    l.slug AS location_slug,
    l.name AS location_name,
    s.id AS slot_id,
    sv.name AS service_name,
    COALESCE(p.display_name, '') AS practitioner_name,
    COALESCE(r.name, '') AS room_name,
    s.start_at,
    s.end_at,
    TRUE AS is_waitlist
  FROM waitlist_entries w
  JOIN appointment_slots s ON s.id = w.slot_id
  JOIN services sv ON sv.id = w.service_id
  LEFT JOIN practitioners p ON p.id = COALESCE(w.practitioner_id, s.practitioner_id)
  LEFT JOIN rooms r ON r.id = s.room_id
  JOIN locations l ON l.id = w.location_id
  WHERE w.location_id = $1
    AND w.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
    AND w.status = 'active'
)
SELECT
  u.booking_id,
  u.status,
  u.booked_at,
  u.guest_name,
  u.guest_email,
  u.guest_phone,
  u.cancel_reason,
  u.location_id,
  u.location_slug,
  u.location_name,
  u.slot_id,
  u.service_name,
  u.practitioner_name,
  u.room_name,
  u.start_at,
  u.end_at,
  u.is_waitlist
FROM unified u
JOIN locations l ON l.id = u.location_id
WHERE (
    COALESCE($4::text, '') = ''
    OR u.status = $4
  )
  AND (
    COALESCE($5::text, '') = ''
    OR (u.start_at AT TIME ZONE l.timezone)::date >= $5::date
  )
  AND (
    COALESCE($6::text, '') = ''
    OR (u.start_at AT TIME ZONE l.timezone)::date <= $6::date
  )
ORDER BY u.start_at ASC, u.booked_at DESC
LIMIT $2
OFFSET $3
`

type ListHostBookingsByLocationParams struct {
	LocationID   uuid.UUID   `json:"location_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	FilterStatus pgtype.Text `json:"filter_status"`
	FromDate     pgtype.Text `json:"from_date"`
	ToDate       pgtype.Text `json:"to_date"`
}

type ListHostBookingsByLocationRow struct {
	BookingID        uuid.UUID   `json:"booking_id"`
	Status           string      `json:"status"`
	BookedAt         time.Time   `json:"booked_at"`
	GuestName        string      `json:"guest_name"`
	GuestEmail       string      `json:"guest_email"`
	GuestPhone       pgtype.Text `json:"guest_phone"`
	CancelReason     pgtype.Text `json:"cancel_reason"`
	LocationID       uuid.UUID   `json:"location_id"`
	LocationSlug     string      `json:"location_slug"`
	LocationName     string      `json:"location_name"`
	SlotID           uuid.UUID   `json:"slot_id"`
	ServiceName      string      `json:"service_name"`
	PractitionerName string      `json:"practitioner_name"`
	RoomName         string      `json:"room_name"`
	StartAt          time.Time   `json:"start_at"`
	EndAt            time.Time   `json:"end_at"`
	IsWaitlist       bool        `json:"is_waitlist"`
}

func (q *Queries) ListHostBookingsByLocation(ctx context.Context, arg ListHostBookingsByLocationParams) ([]ListHostBookingsByLocationRow, error) {
	rows, err := q.db.Query(ctx, listHostBookingsByLocation,
		arg.LocationID,
		arg.Limit,
		arg.Offset,
		arg.FilterStatus,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostBookingsByLocationRow{}
	for rows.Next() {
		var i ListHostBookingsByLocationRow
		if err := rows.Scan(
			&i.BookingID,
			&i.Status,
			&i.BookedAt,
			&i.GuestName,
			&i.GuestEmail,
			&i.GuestPhone,
			&i.CancelReason,
			&i.LocationID,
			&i.LocationSlug,
			&i.LocationName,
			&i.SlotID,
			&i.ServiceName,
			&i.PractitionerName,
			&i.RoomName,
			&i.StartAt,
			&i.EndAt,
			&i.IsWaitlist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostLocationsByOwner = `-- name: ListHostLocationsByOwner :many
SELECT
  id,
  owner_username,
  slug,
  name,
  timezone,
  is_active,
  booking_requires_host_approval,
  COALESCE(cancellation_min_hours_before_start, 24)::int AS effective_cancellation_min_hours_before_start,
  logo_url,
  primary_color,
  accent_color,
  background_color,
  font_family
FROM locations
WHERE owner_username = $1
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
ORDER BY name ASC
`

type ListHostLocationsByOwnerRow struct {
	ID                                       uuid.UUID   `json:"id"`
	OwnerUsername                            string      `json:"owner_username"`
	Slug                                     string      `json:"slug"`
	Name                                     string      `json:"name"`
	Timezone                                 string      `json:"timezone"`
	IsActive                                 bool        `json:"is_active"`
	BookingRequiresHostApproval              bool        `json:"booking_requires_host_approval"`
	EffectiveCancellationMinHoursBeforeStart int32       `json:"effective_cancellation_min_hours_before_start"`
	LogoUrl                                  pgtype.Text `json:"logo_url"`
	PrimaryColor                             pgtype.Text `json:"primary_color"`
	AccentColor                              pgtype.Text `json:"accent_color"`
	BackgroundColor                          pgtype.Text `json:"background_color"`
	FontFamily                               pgtype.Text `json:"font_family"`
}

func (q *Queries) ListHostLocationsByOwner(ctx context.Context, ownerUsername string) ([]ListHostLocationsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listHostLocationsByOwner, ownerUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostLocationsByOwnerRow{}
	for rows.Next() {
		var i ListHostLocationsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUsername,
			&i.Slug,
			&i.Name,
			&i.Timezone,
			&i.IsActive,
			&i.BookingRequiresHostApproval,
			&i.EffectiveCancellationMinHoursBeforeStart,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.AccentColor,
			&i.BackgroundColor,
			&i.FontFamily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostServicesByLocation = `-- name: ListHostServicesByLocation :many
SELECT
  id,
  location_id,
  name,
  description,
  duration_minutes,
  price_minor_units,
  currency,
  is_active,
  cancellation_min_hours_before_start
FROM services s
WHERE s.location_id = $1
  AND s.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND (
    $4::bool IS NULL
    OR s.is_active = $4
  )
ORDER BY s.name ASC
LIMIT $2
OFFSET $3
`

type ListHostServicesByLocationParams struct {
	LocationID     uuid.UUID   `json:"location_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
	FilterIsActive pgtype.Bool `json:"filter_is_active"`
}

type ListHostServicesByLocationRow struct {
	ID                              uuid.UUID   `json:"id"`
	LocationID                      uuid.UUID   `json:"location_id"`
	Name                            string      `json:"name"`
	Description                     string      `json:"description"`
	DurationMinutes                 int32       `json:"duration_minutes"`
	PriceMinorUnits                 int64       `json:"price_minor_units"`
	Currency                        string      `json:"currency"`
	IsActive                        bool        `json:"is_active"`
	CancellationMinHoursBeforeStart pgtype.Int4 `json:"cancellation_min_hours_before_start"`
}

func (q *Queries) ListHostServicesByLocation(ctx context.Context, arg ListHostServicesByLocationParams) ([]ListHostServicesByLocationRow, error) {
	rows, err := q.db.Query(ctx, listHostServicesByLocation,
		arg.LocationID,
		arg.Limit,
		arg.Offset,
		arg.FilterIsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostServicesByLocationRow{}
	for rows.Next() {
		var i ListHostServicesByLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.PriceMinorUnits,
			&i.Currency,
			&i.IsActive,
			&i.CancellationMinHoursBeforeStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostSlotsByLocation = `-- name: ListHostSlotsByLocation :many
SELECT
  s.id,
  s.location_id,
  s.service_id,
  sv.name AS service_name,
  s.practitioner_id,
  COALESCE(p.display_name, '') AS practitioner_name,
  s.room_id,
  COALESCE(r.name, '') AS room_name,
  s.start_at,
  s.end_at,
  s.capacity,
  s.booked_count,
  s.status
FROM appointment_slots s
JOIN services sv ON sv.id = s.service_id
LEFT JOIN practitioners p ON p.id = s.practitioner_id
LEFT JOIN rooms r ON r.id = s.room_id
WHERE s.location_id = $1
  AND s.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND sv.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND (
    COALESCE($4::text, '') = ''
    OR s.status = $4
  )
  AND (
    COALESCE($5::text, '') = ''
    OR s.start_at::date >= $5::date
  )
  AND (
    COALESCE($6::text, '') = ''
    OR s.start_at::date <= $6::date
  )
  AND (
    COALESCE($7::uuid, NULL::uuid) IS NULL
    OR s.service_id = $7
  )
  AND (
    COALESCE($8::uuid, NULL::uuid) IS NULL
    OR s.practitioner_id = $8
  )
  AND (
    COALESCE($9::uuid, NULL::uuid) IS NULL
    OR s.room_id = $9
  )
ORDER BY s.start_at ASC
LIMIT $2
OFFSET $3
`

type ListHostSlotsByLocationParams struct {
	LocationID           uuid.UUID   `json:"location_id"`
	Limit                int32       `json:"limit"`
	Offset               int32       `json:"offset"`
	FilterStatus         pgtype.Text `json:"filter_status"`
	FromDate             pgtype.Text `json:"from_date"`
	ToDate               pgtype.Text `json:"to_date"`
	FilterServiceID      pgtype.UUID `json:"filter_service_id"`
	FilterPractitionerID pgtype.UUID `json:"filter_practitioner_id"`
	FilterRoomID         pgtype.UUID `json:"filter_room_id"`
}

type ListHostSlotsByLocationRow struct {
	ID               uuid.UUID   `json:"id"`
	LocationID       uuid.UUID   `json:"location_id"`
	ServiceID        uuid.UUID   `json:"service_id"`
	ServiceName      string      `json:"service_name"`
	PractitionerID   pgtype.UUID `json:"practitioner_id"`
	PractitionerName string      `json:"practitioner_name"`
	RoomID           pgtype.UUID `json:"room_id"`
	RoomName         string      `json:"room_name"`
	StartAt          time.Time   `json:"start_at"`
	EndAt            time.Time   `json:"end_at"`
	Capacity         int32       `json:"capacity"`
	BookedCount      int32       `json:"booked_count"`
	Status           string      `json:"status"`
}

func (q *Queries) ListHostSlotsByLocation(ctx context.Context, arg ListHostSlotsByLocationParams) ([]ListHostSlotsByLocationRow, error) {
	rows, err := q.db.Query(ctx, listHostSlotsByLocation,
		arg.LocationID,
		arg.Limit,
		arg.Offset,
		arg.FilterStatus,
		arg.FromDate,
		arg.ToDate,
		arg.FilterServiceID,
		arg.FilterPractitionerID,
		arg.FilterRoomID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostSlotsByLocationRow{}
	for rows.Next() {
		var i ListHostSlotsByLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.ServiceID,
			&i.ServiceName,
			&i.PractitionerID,
			&i.PractitionerName,
			&i.RoomID,
			&i.RoomName,
			&i.StartAt,
			&i.EndAt,
			&i.Capacity,
			&i.BookedCount,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyBookings = `-- name: ListMyBookings :many
SELECT
  b.id AS booking_id,
  b.status,
  b.booked_at,
  b.guest_name,
  b.guest_email,
  b.guest_phone,
  b.cancel_reason,
  l.id AS location_id,
  l.slug AS location_slug,
  l.name AS location_name,
  s.id AS slot_id,
  sv.name AS service_name,
  COALESCE(p.display_name, '') AS practitioner_name,
  COALESCE(r.name, '') AS room_name,
  s.start_at,
  s.end_at,
  EXISTS (
    SELECT 1
    FROM waitlist_entries w
    WHERE w.location_id = b.location_id
      AND w.service_id = s.service_id
      AND lower(w.guest_email) = lower(b.guest_email)
  ) AS is_waitlist
FROM bookings b
JOIN appointment_slots s ON s.id = b.slot_id
JOIN services sv ON sv.id = s.service_id
LEFT JOIN practitioners p ON p.id = s.practitioner_id
LEFT JOIN rooms r ON r.id = s.room_id
JOIN locations l ON l.id = b.location_id
WHERE (
    b.client_username = $1
    OR (
    COALESCE($4::text, '') <> ''
    AND lower(b.guest_email) = lower($4)
    )
  )
  AND b.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND (
    COALESCE($5::text, '') = ''
    OR b.status = $5
  )
  AND (
    COALESCE($6::text, '') = ''
    OR (s.start_at AT TIME ZONE l.timezone)::date >= $6::date
  )
  AND (
    COALESCE($7::text, '') = ''
    OR (s.start_at AT TIME ZONE l.timezone)::date <= $7::date
  )
ORDER BY s.start_at ASC, b.booked_at DESC
LIMIT $2
OFFSET $3
`

type ListMyBookingsParams struct {
	ClientUsername   pgtype.Text `json:"client_username"`
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	FilterGuestEmail pgtype.Text `json:"filter_guest_email"`
	FilterStatus     pgtype.Text `json:"filter_status"`
	FromDate         pgtype.Text `json:"from_date"`
	ToDate           pgtype.Text `json:"to_date"`
}

type ListMyBookingsRow struct {
	BookingID        uuid.UUID   `json:"booking_id"`
	Status           string      `json:"status"`
	BookedAt         time.Time   `json:"booked_at"`
	GuestName        string      `json:"guest_name"`
	GuestEmail       string      `json:"guest_email"`
	GuestPhone       pgtype.Text `json:"guest_phone"`
	CancelReason     pgtype.Text `json:"cancel_reason"`
	LocationID       uuid.UUID   `json:"location_id"`
	LocationSlug     string      `json:"location_slug"`
	LocationName     string      `json:"location_name"`
	SlotID           uuid.UUID   `json:"slot_id"`
	ServiceName      string      `json:"service_name"`
	PractitionerName string      `json:"practitioner_name"`
	RoomName         string      `json:"room_name"`
	StartAt          time.Time   `json:"start_at"`
	EndAt            time.Time   `json:"end_at"`
	IsWaitlist       bool        `json:"is_waitlist"`
}

func (q *Queries) ListMyBookings(ctx context.Context, arg ListMyBookingsParams) ([]ListMyBookingsRow, error) {
	rows, err := q.db.Query(ctx, listMyBookings,
		arg.ClientUsername,
		arg.Limit,
		arg.Offset,
		arg.FilterGuestEmail,
		arg.FilterStatus,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyBookingsRow{}
	for rows.Next() {
		var i ListMyBookingsRow
		if err := rows.Scan(
			&i.BookingID,
			&i.Status,
			&i.BookedAt,
			&i.GuestName,
			&i.GuestEmail,
			&i.GuestPhone,
			&i.CancelReason,
			&i.LocationID,
			&i.LocationSlug,
			&i.LocationName,
			&i.SlotID,
			&i.ServiceName,
			&i.PractitionerName,
			&i.RoomName,
			&i.StartAt,
			&i.EndAt,
			&i.IsWaitlist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicFilterPractitionersByLocationSlug = `-- name: ListPublicFilterPractitionersByLocationSlug :many
SELECT p.id, p.display_name
FROM practitioners p
JOIN locations l ON l.id = p.location_id
WHERE l.slug = $1
  AND l.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND p.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND p.is_active = true
ORDER BY p.display_name ASC
`

type ListPublicFilterPractitionersByLocationSlugRow struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) ListPublicFilterPractitionersByLocationSlug(ctx context.Context, slug string) ([]ListPublicFilterPractitionersByLocationSlugRow, error) {
	rows, err := q.db.Query(ctx, listPublicFilterPractitionersByLocationSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicFilterPractitionersByLocationSlugRow{}
	for rows.Next() {
		var i ListPublicFilterPractitionersByLocationSlugRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicFilterRoomsByLocationSlug = `-- name: ListPublicFilterRoomsByLocationSlug :many
SELECT r.id, r.name
FROM rooms r
JOIN locations l ON l.id = r.location_id
WHERE l.slug = $1
  AND l.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND r.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND r.is_active = true
ORDER BY r.name ASC
`

type ListPublicFilterRoomsByLocationSlugRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListPublicFilterRoomsByLocationSlug(ctx context.Context, slug string) ([]ListPublicFilterRoomsByLocationSlugRow, error) {
	rows, err := q.db.Query(ctx, listPublicFilterRoomsByLocationSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicFilterRoomsByLocationSlugRow{}
	for rows.Next() {
		var i ListPublicFilterRoomsByLocationSlugRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicFilterServicesByLocationSlug = `-- name: ListPublicFilterServicesByLocationSlug :many
SELECT sv.id, sv.name
FROM services sv
JOIN locations l ON l.id = sv.location_id
WHERE l.slug = $1
  AND l.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND sv.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND sv.is_active = true
ORDER BY sv.name ASC
`

type ListPublicFilterServicesByLocationSlugRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListPublicFilterServicesByLocationSlug(ctx context.Context, slug string) ([]ListPublicFilterServicesByLocationSlugRow, error) {
	rows, err := q.db.Query(ctx, listPublicFilterServicesByLocationSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicFilterServicesByLocationSlugRow{}
	for rows.Next() {
		var i ListPublicFilterServicesByLocationSlugRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicLocations = `-- name: ListPublicLocations :many
SELECT DISTINCT
  l.id,
  l.slug,
  l.name,
  l.timezone,
  l.booking_requires_host_approval,
  l.logo_url,
  l.primary_color,
  l.accent_color,
  l.background_color,
  l.font_family
FROM locations l
JOIN appointment_slots s ON s.location_id = l.id
JOIN services sv ON sv.id = s.service_id
WHERE l.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND l.is_active = true
  AND s.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND s.start_at > now()
  AND sv.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND sv.is_active = true
ORDER BY l.name ASC
`

type ListPublicLocationsRow struct {
	ID                          uuid.UUID   `json:"id"`
	Slug                        string      `json:"slug"`
	Name                        string      `json:"name"`
	Timezone                    string      `json:"timezone"`
	BookingRequiresHostApproval bool        `json:"booking_requires_host_approval"`
	LogoUrl                     pgtype.Text `json:"logo_url"`
	PrimaryColor                pgtype.Text `json:"primary_color"`
	AccentColor                 pgtype.Text `json:"accent_color"`
	BackgroundColor             pgtype.Text `json:"background_color"`
	FontFamily                  pgtype.Text `json:"font_family"`
}

func (q *Queries) ListPublicLocations(ctx context.Context) ([]ListPublicLocationsRow, error) {
	rows, err := q.db.Query(ctx, listPublicLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicLocationsRow{}
	for rows.Next() {
		var i ListPublicLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Timezone,
			&i.BookingRequiresHostApproval,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.AccentColor,
			&i.BackgroundColor,
			&i.FontFamily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicSlotsByLocationSlug = `-- name: ListPublicSlotsByLocationSlug :many
SELECT
  s.id AS slot_id,
  s.start_at,
  s.end_at,
  s.status AS slot_status,
  s.capacity,
  s.booked_count,
  sv.id AS service_id,
  sv.name AS service_name,
  sv.duration_minutes,
  sv.price_minor_units,
  sv.currency,
  COALESCE(
    sv.cancellation_min_hours_before_start,
    l.cancellation_min_hours_before_start,
    24
  )::int AS effective_cancellation_min_hours_before_start,
  p.id AS practitioner_id,
  p.display_name AS practitioner_display_name,
  r.id AS room_id,
  r.name AS room_name,
  l.id AS location_id,
  l.slug AS location_slug,
  l.name AS location_name,
  l.timezone AS location_timezone,
  l.booking_requires_host_approval,
  l.logo_url AS location_logo_url,
  l.primary_color AS location_primary_color,
  l.accent_color AS location_accent_color,
  l.background_color AS location_background_color,
  l.font_family AS location_font_family
FROM locations l
JOIN appointment_slots s ON s.location_id = l.id
JOIN services sv ON sv.id = s.service_id
LEFT JOIN practitioners p ON p.id = s.practitioner_id
LEFT JOIN rooms r ON r.id = s.room_id
WHERE l.slug = $1
  AND l.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND l.is_active = true
  AND s.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND sv.deleted_at = '0001-01-01 00:00:00Z'::timestamptz
  AND sv.is_active = true
ORDER BY s.start_at ASC
`

type ListPublicSlotsByLocationSlugRow struct {
	SlotID                                   uuid.UUID   `json:"slot_id"`
	StartAt                                  time.Time   `json:"start_at"`
	EndAt                                    time.Time   `json:"end_at"`
	SlotStatus                               string      `json:"slot_status"`
	Capacity                                 int32       `json:"capacity"`
	BookedCount                              int32       `json:"booked_count"`
	ServiceID                                uuid.UUID   `json:"service_id"`
	ServiceName                              string      `json:"service_name"`
	DurationMinutes                          int32       `json:"duration_minutes"`
	PriceMinorUnits                          int64       `json:"price_minor_units"`
	Currency                                 string      `json:"currency"`
	EffectiveCancellationMinHoursBeforeStart int32       `json:"effective_cancellation_min_hours_before_start"`
	PractitionerID                           pgtype.UUID `json:"practitioner_id"`
	PractitionerDisplayName                  pgtype.Text `json:"practitioner_display_name"`
	RoomID                                   pgtype.UUID `json:"room_id"`
	RoomName                                 pgtype.Text `json:"room_name"`
	LocationID                               uuid.UUID   `json:"location_id"`
	LocationSlug                             string      `json:"location_slug"`
	LocationName                             string      `json:"location_name"`
	LocationTimezone                         string      `json:"location_timezone"`
	BookingRequiresHostApproval              bool        `json:"booking_requires_host_approval"`
	LocationLogoUrl                          pgtype.Text `json:"location_logo_url"`
	LocationPrimaryColor                     pgtype.Text `json:"location_primary_color"`
	LocationAccentColor                      pgtype.Text `json:"location_accent_color"`
	LocationBackgroundColor                  pgtype.Text `json:"location_background_color"`
	LocationFontFamily                       pgtype.Text `json:"location_font_family"`
}

func (q *Queries) ListPublicSlotsByLocationSlug(ctx context.Context, slug string) ([]ListPublicSlotsByLocationSlugRow, error) {
	rows, err := q.db.Query(ctx, listPublicSlotsByLocationSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicSlotsByLocationSlugRow{}
	for rows.Next() {
		var i ListPublicSlotsByLocationSlugRow
		if err := rows.Scan(
			&i.SlotID,
			&i.StartAt,
			&i.EndAt,
			&i.SlotStatus,
			&i.Capacity,
			&i.BookedCount,
			&i.ServiceID,
			&i.ServiceName,
			&i.DurationMinutes,
			&i.PriceMinorUnits,
			&i.Currency,
			&i.EffectiveCancellationMinHoursBeforeStart,
			&i.PractitionerID,
			&i.PractitionerDisplayName,
			&i.RoomID,
			&i.RoomName,
			&i.LocationID,
			&i.LocationSlug,
			&i.LocationName,
			&i.LocationTimezone,
			&i.BookingRequiresHostApproval,
			&i.LocationLogoUrl,
			&i.LocationPrimaryColor,
			&i.LocationAccentColor,
			&i.LocationBackgroundColor,
			&i.LocationFontFamily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBookingCancelled = `-- name: MarkBookingCancelled :one
UPDATE bookings
SET
  status = 'cancelled',
  cancelled_at = now(),
  cancel_reason = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, location_id, slot_id, status, guest_name, guest_email, guest_phone, guest_notes, client_username, booked_at, cancelled_at, cancel_reason, cancel_token_hash, created_at, updated_at, deleted_at
`

type MarkBookingCancelledParams struct {
	ID           uuid.UUID   `json:"id"`
	CancelReason pgtype.Text `json:"cancel_reason"`
}

func (q *Queries) MarkBookingCancelled(ctx context.Context, arg MarkBookingCancelledParams) (Booking, error) {
	row := q.db.QueryRow(ctx, markBookingCancelled, arg.ID, arg.CancelReason)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.SlotID,
		&i.Status,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.GuestNotes,
		&i.ClientUsername,
		&i.BookedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CancelTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markBookingNoShow = `-- name: MarkBookingNoShow :one
UPDATE bookings
SET
  status = 'no_show',
  updated_at = now()
WHERE id = $1
  AND status = 'confirmed'
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
RETURNING id, location_id, slot_id, status, guest_name, guest_email, guest_phone, guest_notes, client_username, booked_at, cancelled_at, cancel_reason, cancel_token_hash, created_at, updated_at, deleted_at
`

func (q *Queries) MarkBookingNoShow(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, markBookingNoShow, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.SlotID,
		&i.Status,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.GuestNotes,
		&i.ClientUsername,
		&i.BookedAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CancelTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateHostLocationService = `-- name: UpdateHostLocationService :one
UPDATE services
SET
  name = COALESCE($3, name),
  description = COALESCE($4, description),
  duration_minutes = COALESCE($5, duration_minutes),
  price_minor_units = COALESCE($6, price_minor_units),
  currency = COALESCE($7, currency),
  is_active = COALESCE($8, is_active),
  cancellation_min_hours_before_start = COALESCE($9, cancellation_min_hours_before_start),
  updated_at = now()
WHERE id = $1
  AND location_id = $2
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
RETURNING id, location_id, name, description, duration_minutes, price_minor_units, currency, is_active, cancellation_min_hours_before_start, created_at, updated_at, deleted_at
`

type UpdateHostLocationServiceParams struct {
	ID                              uuid.UUID   `json:"id"`
	LocationID                      uuid.UUID   `json:"location_id"`
	Name                            pgtype.Text `json:"name"`
	Description                     pgtype.Text `json:"description"`
	DurationMinutes                 pgtype.Int4 `json:"duration_minutes"`
	PriceMinorUnits                 pgtype.Int8 `json:"price_minor_units"`
	Currency                        pgtype.Text `json:"currency"`
	IsActive                        pgtype.Bool `json:"is_active"`
	CancellationMinHoursBeforeStart pgtype.Int4 `json:"cancellation_min_hours_before_start"`
}

func (q *Queries) UpdateHostLocationService(ctx context.Context, arg UpdateHostLocationServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateHostLocationService,
		arg.ID,
		arg.LocationID,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.PriceMinorUnits,
		arg.Currency,
		arg.IsActive,
		arg.CancellationMinHoursBeforeStart,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.PriceMinorUnits,
		&i.Currency,
		&i.IsActive,
		&i.CancellationMinHoursBeforeStart,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateHostLocationSlot = `-- name: UpdateHostLocationSlot :one
UPDATE appointment_slots
SET
  service_id = COALESCE($3, service_id),
  practitioner_id = COALESCE($4, practitioner_id),
  room_id = COALESCE($5, room_id),
  start_at = COALESCE($6, start_at),
  end_at = COALESCE($7, end_at),
  capacity = COALESCE($8, capacity),
  status = COALESCE($9, status),
  updated_at = now()
WHERE id = $1
  AND location_id = $2
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
RETURNING id, location_id, service_id, practitioner_id, room_id, start_at, end_at, capacity, booked_count, status, created_at, updated_at, deleted_at
`

type UpdateHostLocationSlotParams struct {
	ID             uuid.UUID          `json:"id"`
	LocationID     uuid.UUID          `json:"location_id"`
	ServiceID      pgtype.UUID        `json:"service_id"`
	PractitionerID pgtype.UUID        `json:"practitioner_id"`
	RoomID         pgtype.UUID        `json:"room_id"`
	StartAt        pgtype.Timestamptz `json:"start_at"`
	EndAt          pgtype.Timestamptz `json:"end_at"`
	Capacity       pgtype.Int4        `json:"capacity"`
	Status         pgtype.Text        `json:"status"`
}

func (q *Queries) UpdateHostLocationSlot(ctx context.Context, arg UpdateHostLocationSlotParams) (AppointmentSlot, error) {
	row := q.db.QueryRow(ctx, updateHostLocationSlot,
		arg.ID,
		arg.LocationID,
		arg.ServiceID,
		arg.PractitionerID,
		arg.RoomID,
		arg.StartAt,
		arg.EndAt,
		arg.Capacity,
		arg.Status,
	)
	var i AppointmentSlot
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.ServiceID,
		&i.PractitionerID,
		&i.RoomID,
		&i.StartAt,
		&i.EndAt,
		&i.Capacity,
		&i.BookedCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET
  name = COALESCE($2, name),
  slug = COALESCE($3, slug),
  timezone = COALESCE($4, timezone),
  is_active = COALESCE($5, is_active),
  booking_requires_host_approval = COALESCE($6, booking_requires_host_approval),
  updated_at = now()
WHERE id = $1
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
RETURNING id, owner_username, name, slug, timezone, is_active, booking_requires_host_approval, cancellation_min_hours_before_start, created_at, updated_at, deleted_at, logo_url, primary_color, accent_color, font_family, background_color
`

type UpdateLocationParams struct {
	ID                          uuid.UUID   `json:"id"`
	Name                        pgtype.Text `json:"name"`
	Slug                        pgtype.Text `json:"slug"`
	Timezone                    pgtype.Text `json:"timezone"`
	IsActive                    pgtype.Bool `json:"is_active"`
	BookingRequiresHostApproval pgtype.Bool `json:"booking_requires_host_approval"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Timezone,
		arg.IsActive,
		arg.BookingRequiresHostApproval,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OwnerUsername,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.IsActive,
		&i.BookingRequiresHostApproval,
		&i.CancellationMinHoursBeforeStart,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.FontFamily,
		&i.BackgroundColor,
	)
	return i, err
}

const updateLocationBranding = `-- name: UpdateLocationBranding :one
UPDATE locations
SET
  logo_url = CASE
    WHEN $1::bool THEN NULL
    WHEN $2::bool THEN NULL
    WHEN $3::bool THEN $4
    ELSE logo_url
  END,
  primary_color = CASE
    WHEN $1::bool THEN NULL
    WHEN $5::bool THEN NULL
    WHEN $6::bool THEN $7
    ELSE primary_color
  END,
  accent_color = CASE
    WHEN $1::bool THEN NULL
    WHEN $8::bool THEN NULL
    WHEN $9::bool THEN $10
    ELSE accent_color
  END,
  background_color = CASE
    WHEN $1::bool THEN NULL
    WHEN $11::bool THEN NULL
    WHEN $12::bool THEN $13
    ELSE background_color
  END,
  font_family = CASE
    WHEN $1::bool THEN NULL
    WHEN $14::bool THEN NULL
    WHEN $15::bool THEN $16
    ELSE font_family
  END,
  updated_at = now()
WHERE id = $17
  AND deleted_at = '0001-01-01 00:00:00Z'::timestamptz
RETURNING id, owner_username, name, slug, timezone, is_active, booking_requires_host_approval, cancellation_min_hours_before_start, created_at, updated_at, deleted_at, logo_url, primary_color, accent_color, font_family, background_color
`

type UpdateLocationBrandingParams struct {
	ResetBranding        bool        `json:"reset_branding"`
	ClearLogoUrl         bool        `json:"clear_logo_url"`
	SetLogoUrl           bool        `json:"set_logo_url"`
	LogoUrl              pgtype.Text `json:"logo_url"`
	ClearPrimaryColor    bool        `json:"clear_primary_color"`
	SetPrimaryColor      bool        `json:"set_primary_color"`
	PrimaryColor         pgtype.Text `json:"primary_color"`
	ClearAccentColor     bool        `json:"clear_accent_color"`
	SetAccentColor       bool        `json:"set_accent_color"`
	AccentColor          pgtype.Text `json:"accent_color"`
	ClearBackgroundColor bool        `json:"clear_background_color"`
	SetBackgroundColor   bool        `json:"set_background_color"`
	BackgroundColor      pgtype.Text `json:"background_color"`
	ClearFontFamily      bool        `json:"clear_font_family"`
	SetFontFamily        bool        `json:"set_font_family"`
	FontFamily           pgtype.Text `json:"font_family"`
	ID                   uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateLocationBranding(ctx context.Context, arg UpdateLocationBrandingParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocationBranding,
		arg.ResetBranding,
		arg.ClearLogoUrl,
		arg.SetLogoUrl,
		arg.LogoUrl,
		arg.ClearPrimaryColor,
		arg.SetPrimaryColor,
		arg.PrimaryColor,
		arg.ClearAccentColor,
		arg.SetAccentColor,
		arg.AccentColor,
		arg.ClearBackgroundColor,
		arg.SetBackgroundColor,
		arg.BackgroundColor,
		arg.ClearFontFamily,
		arg.SetFontFamily,
		arg.FontFamily,
		arg.ID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OwnerUsername,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.IsActive,
		&i.BookingRequiresHostApproval,
		&i.CancellationMinHoursBeforeStart,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.FontFamily,
		&i.BackgroundColor,
	)
	return i, err
}

const updateSlotCounters = `-- name: UpdateSlotCounters :one
UPDATE appointment_slots
SET
  booked_count = $2,
  status = $3,
  updated_at = now()
WHERE id = $1
RETURNING id, location_id, service_id, practitioner_id, room_id, start_at, end_at, capacity, booked_count, status, created_at, updated_at, deleted_at
`

type UpdateSlotCountersParams struct {
	ID          uuid.UUID `json:"id"`
	BookedCount int32     `json:"booked_count"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdateSlotCounters(ctx context.Context, arg UpdateSlotCountersParams) (AppointmentSlot, error) {
	row := q.db.QueryRow(ctx, updateSlotCounters, arg.ID, arg.BookedCount, arg.Status)
	var i AppointmentSlot
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.ServiceID,
		&i.PractitionerID,
		&i.RoomID,
		&i.StartAt,
		&i.EndAt,
		&i.Capacity,
		&i.BookedCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
