// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ConfirmBooking(ctx context.Context, id uuid.UUID) (Booking, error)
	CountHostBookingsByLocation(ctx context.Context, arg CountHostBookingsByLocationParams) (int32, error)
	CountHostServicesByLocation(ctx context.Context, arg CountHostServicesByLocationParams) (int32, error)
	CountHostSlotsByLocation(ctx context.Context, arg CountHostSlotsByLocationParams) (int32, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateHostLocationService(ctx context.Context, arg CreateHostLocationServiceParams) (Service, error)
	CreateHostLocationSlot(ctx context.Context, arg CreateHostLocationSlotParams) (AppointmentSlot, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerificationEmail(ctx context.Context, arg CreateVerificationEmailParams) (VerificationEmail, error)
	GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error)
	GetBookingForCancelByIDForUpdate(ctx context.Context, id uuid.UUID) (GetBookingForCancelByIDForUpdateRow, error)
	GetBookingForHostOpByIDForUpdate(ctx context.Context, id uuid.UUID) (GetBookingForHostOpByIDForUpdateRow, error)
	GetHostServiceByID(ctx context.Context, arg GetHostServiceByIDParams) (Service, error)
	GetHostSlotByID(ctx context.Context, arg GetHostSlotByIDParams) (AppointmentSlot, error)
	GetLocationByID(ctx context.Context, id uuid.UUID) (Location, error)
	GetLocationBySlug(ctx context.Context, slug string) (Location, error)
	GetPractitionerByID(ctx context.Context, id uuid.UUID) (Practitioner, error)
	GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error)
	GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetSlotForUpdate(ctx context.Context, arg GetSlotForUpdateParams) (AppointmentSlot, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVerificationEmailByToken(ctx context.Context, verificationToken string) (VerificationEmail, error)
	ListAllHostLocations(ctx context.Context) ([]ListAllHostLocationsRow, error)
	ListHostBookingsByLocation(ctx context.Context, arg ListHostBookingsByLocationParams) ([]ListHostBookingsByLocationRow, error)
	ListHostLocationsByOwner(ctx context.Context, ownerUsername string) ([]ListHostLocationsByOwnerRow, error)
	ListHostServicesByLocation(ctx context.Context, arg ListHostServicesByLocationParams) ([]ListHostServicesByLocationRow, error)
	ListHostSlotsByLocation(ctx context.Context, arg ListHostSlotsByLocationParams) ([]ListHostSlotsByLocationRow, error)
	ListPublicFilterPractitionersByLocationSlug(ctx context.Context, slug string) ([]ListPublicFilterPractitionersByLocationSlugRow, error)
	ListPublicFilterRoomsByLocationSlug(ctx context.Context, slug string) ([]ListPublicFilterRoomsByLocationSlugRow, error)
	ListPublicFilterServicesByLocationSlug(ctx context.Context, slug string) ([]ListPublicFilterServicesByLocationSlugRow, error)
	ListPublicSlotsByLocationSlug(ctx context.Context, slug string) ([]ListPublicSlotsByLocationSlugRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkBookingCancelled(ctx context.Context, arg MarkBookingCancelledParams) (Booking, error)
	UpdateHostLocationService(ctx context.Context, arg UpdateHostLocationServiceParams) (Service, error)
	UpdateHostLocationSlot(ctx context.Context, arg UpdateHostLocationSlotParams) (AppointmentSlot, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateSlotCounters(ctx context.Context, arg UpdateSlotCountersParams) (AppointmentSlot, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserEmailVerified(ctx context.Context, arg UpdateUserEmailVerifiedParams) (User, error)
	UpdateVerificationEmail(ctx context.Context, arg UpdateVerificationEmailParams) (VerificationEmail, error)
}

var _ Querier = (*Queries)(nil)
