// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: verification_email.sql

package db

import (
	"context"
)

const createVerificationEmail = `-- name: CreateVerificationEmail :one
INSERT INTO verification_emails (
    email,
    verification_token
) VALUES (
    $1, $2
) RETURNING id, email, verification_token, is_used, created_at, token_expiry
`

type CreateVerificationEmailParams struct {
	Email             string `json:"email"`
	VerificationToken string `json:"verification_token"`
}

func (q *Queries) CreateVerificationEmail(ctx context.Context, arg CreateVerificationEmailParams) (VerificationEmail, error) {
	row := q.db.QueryRow(ctx, createVerificationEmail, arg.Email, arg.VerificationToken)
	var i VerificationEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.VerificationToken,
		&i.IsUsed,
		&i.CreatedAt,
		&i.TokenExpiry,
	)
	return i, err
}

const getVerificationEmailByToken = `-- name: GetVerificationEmailByToken :one
SELECT id, email, verification_token, is_used, created_at, token_expiry FROM verification_emails
WHERE verification_token = $1 LIMIT 1
`

func (q *Queries) GetVerificationEmailByToken(ctx context.Context, verificationToken string) (VerificationEmail, error) {
	row := q.db.QueryRow(ctx, getVerificationEmailByToken, verificationToken)
	var i VerificationEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.VerificationToken,
		&i.IsUsed,
		&i.CreatedAt,
		&i.TokenExpiry,
	)
	return i, err
}

const updateVerificationEmail = `-- name: UpdateVerificationEmail :one
UPDATE verification_emails
SET
    is_used = TRUE
WHERE
    email = $1
    AND verification_token = $2
    AND is_used = FALSE
    AND token_expiry > now()
RETURNING id, email, verification_token, is_used, created_at, token_expiry
`

type UpdateVerificationEmailParams struct {
	Email             string `json:"email"`
	VerificationToken string `json:"verification_token"`
}

func (q *Queries) UpdateVerificationEmail(ctx context.Context, arg UpdateVerificationEmailParams) (VerificationEmail, error) {
	row := q.db.QueryRow(ctx, updateVerificationEmail, arg.Email, arg.VerificationToken)
	var i VerificationEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.VerificationToken,
		&i.IsUsed,
		&i.CreatedAt,
		&i.TokenExpiry,
	)
	return i, err
}
