// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.28.1
// source: rpc_public_booking.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicSlotsLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                        string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name                        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Timezone                    string `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	BookingRequiresHostApproval bool   `protobuf:"varint,5,opt,name=booking_requires_host_approval,json=bookingRequiresHostApproval,proto3" json:"booking_requires_host_approval,omitempty"`
}

func (x *PublicSlotsLocation) Reset() {
	*x = PublicSlotsLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicSlotsLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicSlotsLocation) ProtoMessage() {}

func (x *PublicSlotsLocation) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicSlotsLocation.ProtoReflect.Descriptor instead.
func (*PublicSlotsLocation) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{0}
}

func (x *PublicSlotsLocation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicSlotsLocation) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PublicSlotsLocation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublicSlotsLocation) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *PublicSlotsLocation) GetBookingRequiresHostApproval() bool {
	if x != nil {
		return x.BookingRequiresHostApproval
	}
	return false
}

type PublicLocationItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                        string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name                        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Timezone                    string `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	BookingRequiresHostApproval bool   `protobuf:"varint,5,opt,name=booking_requires_host_approval,json=bookingRequiresHostApproval,proto3" json:"booking_requires_host_approval,omitempty"`
}

func (x *PublicLocationItem) Reset() {
	*x = PublicLocationItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicLocationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicLocationItem) ProtoMessage() {}

func (x *PublicLocationItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicLocationItem.ProtoReflect.Descriptor instead.
func (*PublicLocationItem) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{1}
}

func (x *PublicLocationItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicLocationItem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PublicLocationItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublicLocationItem) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *PublicLocationItem) GetBookingRequiresHostApproval() bool {
	if x != nil {
		return x.BookingRequiresHostApproval
	}
	return false
}

type ListPublicLocationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPublicLocationsRequest) Reset() {
	*x = ListPublicLocationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPublicLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicLocationsRequest) ProtoMessage() {}

func (x *ListPublicLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicLocationsRequest.ProtoReflect.Descriptor instead.
func (*ListPublicLocationsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{2}
}

type ListPublicLocationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*PublicLocationItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListPublicLocationsResponse) Reset() {
	*x = ListPublicLocationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPublicLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicLocationsResponse) ProtoMessage() {}

func (x *ListPublicLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicLocationsResponse.ProtoReflect.Descriptor instead.
func (*ListPublicLocationsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{3}
}

func (x *ListPublicLocationsResponse) GetItems() []*PublicLocationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PublicSlotsService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DurationMinutes                 int32  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	PriceMinorUnits                 int64  `protobuf:"varint,4,opt,name=price_minor_units,json=priceMinorUnits,proto3" json:"price_minor_units,omitempty"`
	Currency                        string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	CancellationMinHoursBeforeStart int32  `protobuf:"varint,6,opt,name=cancellation_min_hours_before_start,json=cancellationMinHoursBeforeStart,proto3" json:"cancellation_min_hours_before_start,omitempty"`
}

func (x *PublicSlotsService) Reset() {
	*x = PublicSlotsService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicSlotsService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicSlotsService) ProtoMessage() {}

func (x *PublicSlotsService) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicSlotsService.ProtoReflect.Descriptor instead.
func (*PublicSlotsService) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{4}
}

func (x *PublicSlotsService) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicSlotsService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublicSlotsService) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *PublicSlotsService) GetPriceMinorUnits() int64 {
	if x != nil {
		return x.PriceMinorUnits
	}
	return 0
}

func (x *PublicSlotsService) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PublicSlotsService) GetCancellationMinHoursBeforeStart() int32 {
	if x != nil {
		return x.CancellationMinHoursBeforeStart
	}
	return 0
}

type PublicSlotsPractitioner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
}

func (x *PublicSlotsPractitioner) Reset() {
	*x = PublicSlotsPractitioner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicSlotsPractitioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicSlotsPractitioner) ProtoMessage() {}

func (x *PublicSlotsPractitioner) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicSlotsPractitioner.ProtoReflect.Descriptor instead.
func (*PublicSlotsPractitioner) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{5}
}

func (x *PublicSlotsPractitioner) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicSlotsPractitioner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublicSlotsPractitioner) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type PublicSlotsRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PublicSlotsRoom) Reset() {
	*x = PublicSlotsRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicSlotsRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicSlotsRoom) ProtoMessage() {}

func (x *PublicSlotsRoom) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicSlotsRoom.ProtoReflect.Descriptor instead.
func (*PublicSlotsRoom) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{6}
}

func (x *PublicSlotsRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicSlotsRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PublicSlotsItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotId             string                   `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Service            *PublicSlotsService      `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Practitioner       *PublicSlotsPractitioner `protobuf:"bytes,3,opt,name=practitioner,proto3" json:"practitioner,omitempty"`
	Room               *PublicSlotsRoom         `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	StartAt            string                   `protobuf:"bytes,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt              string                   `protobuf:"bytes,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	AvailabilityStatus string                   `protobuf:"bytes,7,opt,name=availability_status,json=availabilityStatus,proto3" json:"availability_status,omitempty"`
	IsBookable         bool                     `protobuf:"varint,8,opt,name=is_bookable,json=isBookable,proto3" json:"is_bookable,omitempty"`
	Capacity           int32                    `protobuf:"varint,9,opt,name=capacity,proto3" json:"capacity,omitempty"`
	BookedCount        int32                    `protobuf:"varint,10,opt,name=booked_count,json=bookedCount,proto3" json:"booked_count,omitempty"`
	SpacesLeft         int32                    `protobuf:"varint,11,opt,name=spaces_left,json=spacesLeft,proto3" json:"spaces_left,omitempty"`
}

func (x *PublicSlotsItem) Reset() {
	*x = PublicSlotsItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicSlotsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicSlotsItem) ProtoMessage() {}

func (x *PublicSlotsItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicSlotsItem.ProtoReflect.Descriptor instead.
func (*PublicSlotsItem) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{7}
}

func (x *PublicSlotsItem) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *PublicSlotsItem) GetService() *PublicSlotsService {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *PublicSlotsItem) GetPractitioner() *PublicSlotsPractitioner {
	if x != nil {
		return x.Practitioner
	}
	return nil
}

func (x *PublicSlotsItem) GetRoom() *PublicSlotsRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *PublicSlotsItem) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *PublicSlotsItem) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *PublicSlotsItem) GetAvailabilityStatus() string {
	if x != nil {
		return x.AvailabilityStatus
	}
	return ""
}

func (x *PublicSlotsItem) GetIsBookable() bool {
	if x != nil {
		return x.IsBookable
	}
	return false
}

func (x *PublicSlotsItem) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *PublicSlotsItem) GetBookedCount() int32 {
	if x != nil {
		return x.BookedCount
	}
	return 0
}

func (x *PublicSlotsItem) GetSpacesLeft() int32 {
	if x != nil {
		return x.SpacesLeft
	}
	return 0
}

type ListPublicSlotsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationSlug   string `protobuf:"bytes,1,opt,name=location_slug,json=locationSlug,proto3" json:"location_slug,omitempty"`
	Search         string `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	ServiceId      string `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	PractitionerId string `protobuf:"bytes,4,opt,name=practitioner_id,json=practitionerId,proto3" json:"practitioner_id,omitempty"`
	RoomId         string `protobuf:"bytes,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Date           string `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	TimeSlot       string `protobuf:"bytes,7,opt,name=time_slot,json=timeSlot,proto3" json:"time_slot,omitempty"`
	OnlyAvailable  bool   `protobuf:"varint,8,opt,name=only_available,json=onlyAvailable,proto3" json:"only_available,omitempty"`
	Limit          int32  `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32  `protobuf:"varint,10,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListPublicSlotsRequest) Reset() {
	*x = ListPublicSlotsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPublicSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicSlotsRequest) ProtoMessage() {}

func (x *ListPublicSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicSlotsRequest.ProtoReflect.Descriptor instead.
func (*ListPublicSlotsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{8}
}

func (x *ListPublicSlotsRequest) GetLocationSlug() string {
	if x != nil {
		return x.LocationSlug
	}
	return ""
}

func (x *ListPublicSlotsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListPublicSlotsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ListPublicSlotsRequest) GetPractitionerId() string {
	if x != nil {
		return x.PractitionerId
	}
	return ""
}

func (x *ListPublicSlotsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ListPublicSlotsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ListPublicSlotsRequest) GetTimeSlot() string {
	if x != nil {
		return x.TimeSlot
	}
	return ""
}

func (x *ListPublicSlotsRequest) GetOnlyAvailable() bool {
	if x != nil {
		return x.OnlyAvailable
	}
	return false
}

func (x *ListPublicSlotsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPublicSlotsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListPublicSlotsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location       *PublicSlotsLocation `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Items          []*PublicSlotsItem   `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount     int32                `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	AvailableCount int32                `protobuf:"varint,4,opt,name=available_count,json=availableCount,proto3" json:"available_count,omitempty"`
	Limit          int32                `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListPublicSlotsResponse) Reset() {
	*x = ListPublicSlotsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPublicSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicSlotsResponse) ProtoMessage() {}

func (x *ListPublicSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicSlotsResponse.ProtoReflect.Descriptor instead.
func (*ListPublicSlotsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{9}
}

func (x *ListPublicSlotsResponse) GetLocation() *PublicSlotsLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *ListPublicSlotsResponse) GetItems() []*PublicSlotsItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListPublicSlotsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListPublicSlotsResponse) GetAvailableCount() int32 {
	if x != nil {
		return x.AvailableCount
	}
	return 0
}

func (x *ListPublicSlotsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPublicSlotsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PublicFilterService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PublicFilterService) Reset() {
	*x = PublicFilterService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicFilterService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicFilterService) ProtoMessage() {}

func (x *PublicFilterService) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicFilterService.ProtoReflect.Descriptor instead.
func (*PublicFilterService) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{10}
}

func (x *PublicFilterService) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicFilterService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PublicFilterPractitioner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
}

func (x *PublicFilterPractitioner) Reset() {
	*x = PublicFilterPractitioner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicFilterPractitioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicFilterPractitioner) ProtoMessage() {}

func (x *PublicFilterPractitioner) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicFilterPractitioner.ProtoReflect.Descriptor instead.
func (*PublicFilterPractitioner) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{11}
}

func (x *PublicFilterPractitioner) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicFilterPractitioner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublicFilterPractitioner) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type PublicFilterRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PublicFilterRoom) Reset() {
	*x = PublicFilterRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicFilterRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicFilterRoom) ProtoMessage() {}

func (x *PublicFilterRoom) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicFilterRoom.ProtoReflect.Descriptor instead.
func (*PublicFilterRoom) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{12}
}

func (x *PublicFilterRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicFilterRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPublicFilterOptionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationSlug string `protobuf:"bytes,1,opt,name=location_slug,json=locationSlug,proto3" json:"location_slug,omitempty"`
}

func (x *GetPublicFilterOptionsRequest) Reset() {
	*x = GetPublicFilterOptionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPublicFilterOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicFilterOptionsRequest) ProtoMessage() {}

func (x *GetPublicFilterOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicFilterOptionsRequest.ProtoReflect.Descriptor instead.
func (*GetPublicFilterOptionsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{13}
}

func (x *GetPublicFilterOptionsRequest) GetLocationSlug() string {
	if x != nil {
		return x.LocationSlug
	}
	return ""
}

type GetPublicFilterOptionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services      []*PublicFilterService      `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Practitioners []*PublicFilterPractitioner `protobuf:"bytes,2,rep,name=practitioners,proto3" json:"practitioners,omitempty"`
	Rooms         []*PublicFilterRoom         `protobuf:"bytes,3,rep,name=rooms,proto3" json:"rooms,omitempty"`
	TimeSlots     []string                    `protobuf:"bytes,4,rep,name=time_slots,json=timeSlots,proto3" json:"time_slots,omitempty"`
}

func (x *GetPublicFilterOptionsResponse) Reset() {
	*x = GetPublicFilterOptionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPublicFilterOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicFilterOptionsResponse) ProtoMessage() {}

func (x *GetPublicFilterOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicFilterOptionsResponse.ProtoReflect.Descriptor instead.
func (*GetPublicFilterOptionsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{14}
}

func (x *GetPublicFilterOptionsResponse) GetServices() []*PublicFilterService {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *GetPublicFilterOptionsResponse) GetPractitioners() []*PublicFilterPractitioner {
	if x != nil {
		return x.Practitioners
	}
	return nil
}

func (x *GetPublicFilterOptionsResponse) GetRooms() []*PublicFilterRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GetPublicFilterOptionsResponse) GetTimeSlots() []string {
	if x != nil {
		return x.TimeSlots
	}
	return nil
}

type CreatePublicBookingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationId string `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	SlotId     string `protobuf:"bytes,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	GuestName  string `protobuf:"bytes,3,opt,name=guest_name,json=guestName,proto3" json:"guest_name,omitempty"`
	GuestEmail string `protobuf:"bytes,4,opt,name=guest_email,json=guestEmail,proto3" json:"guest_email,omitempty"`
	GuestPhone string `protobuf:"bytes,5,opt,name=guest_phone,json=guestPhone,proto3" json:"guest_phone,omitempty"`
	GuestNotes string `protobuf:"bytes,6,opt,name=guest_notes,json=guestNotes,proto3" json:"guest_notes,omitempty"`
}

func (x *CreatePublicBookingRequest) Reset() {
	*x = CreatePublicBookingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePublicBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePublicBookingRequest) ProtoMessage() {}

func (x *CreatePublicBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePublicBookingRequest.ProtoReflect.Descriptor instead.
func (*CreatePublicBookingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{15}
}

func (x *CreatePublicBookingRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *CreatePublicBookingRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *CreatePublicBookingRequest) GetGuestName() string {
	if x != nil {
		return x.GuestName
	}
	return ""
}

func (x *CreatePublicBookingRequest) GetGuestEmail() string {
	if x != nil {
		return x.GuestEmail
	}
	return ""
}

func (x *CreatePublicBookingRequest) GetGuestPhone() string {
	if x != nil {
		return x.GuestPhone
	}
	return ""
}

func (x *CreatePublicBookingRequest) GetGuestNotes() string {
	if x != nil {
		return x.GuestNotes
	}
	return ""
}

type CreatePublicBookingBooking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LocationId     string `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	SlotId         string `protobuf:"bytes,3,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Status         string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	GuestName      string `protobuf:"bytes,5,opt,name=guest_name,json=guestName,proto3" json:"guest_name,omitempty"`
	GuestEmail     string `protobuf:"bytes,6,opt,name=guest_email,json=guestEmail,proto3" json:"guest_email,omitempty"`
	ClientUsername string `protobuf:"bytes,7,opt,name=client_username,json=clientUsername,proto3" json:"client_username,omitempty"`
	BookedAt       string `protobuf:"bytes,8,opt,name=booked_at,json=bookedAt,proto3" json:"booked_at,omitempty"`
}

func (x *CreatePublicBookingBooking) Reset() {
	*x = CreatePublicBookingBooking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePublicBookingBooking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePublicBookingBooking) ProtoMessage() {}

func (x *CreatePublicBookingBooking) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePublicBookingBooking.ProtoReflect.Descriptor instead.
func (*CreatePublicBookingBooking) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{16}
}

func (x *CreatePublicBookingBooking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePublicBookingBooking) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *CreatePublicBookingBooking) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *CreatePublicBookingBooking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePublicBookingBooking) GetGuestName() string {
	if x != nil {
		return x.GuestName
	}
	return ""
}

func (x *CreatePublicBookingBooking) GetGuestEmail() string {
	if x != nil {
		return x.GuestEmail
	}
	return ""
}

func (x *CreatePublicBookingBooking) GetClientUsername() string {
	if x != nil {
		return x.ClientUsername
	}
	return ""
}

func (x *CreatePublicBookingBooking) GetBookedAt() string {
	if x != nil {
		return x.BookedAt
	}
	return ""
}

type CreatePublicBookingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Booking     *CreatePublicBookingBooking `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	CancelToken string                      `protobuf:"bytes,2,opt,name=cancel_token,json=cancelToken,proto3" json:"cancel_token,omitempty"`
}

func (x *CreatePublicBookingResponse) Reset() {
	*x = CreatePublicBookingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePublicBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePublicBookingResponse) ProtoMessage() {}

func (x *CreatePublicBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePublicBookingResponse.ProtoReflect.Descriptor instead.
func (*CreatePublicBookingResponse) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{17}
}

func (x *CreatePublicBookingResponse) GetBooking() *CreatePublicBookingBooking {
	if x != nil {
		return x.Booking
	}
	return nil
}

func (x *CreatePublicBookingResponse) GetCancelToken() string {
	if x != nil {
		return x.CancelToken
	}
	return ""
}

type CancelPublicBookingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingId    string `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	CancelToken  string `protobuf:"bytes,2,opt,name=cancel_token,json=cancelToken,proto3" json:"cancel_token,omitempty"`
	CancelReason string `protobuf:"bytes,3,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
}

func (x *CancelPublicBookingRequest) Reset() {
	*x = CancelPublicBookingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelPublicBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPublicBookingRequest) ProtoMessage() {}

func (x *CancelPublicBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPublicBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelPublicBookingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{18}
}

func (x *CancelPublicBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CancelPublicBookingRequest) GetCancelToken() string {
	if x != nil {
		return x.CancelToken
	}
	return ""
}

func (x *CancelPublicBookingRequest) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

type CancelPublicBookingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelPublicBookingResponse) Reset() {
	*x = CancelPublicBookingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelPublicBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPublicBookingResponse) ProtoMessage() {}

func (x *CancelPublicBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPublicBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelPublicBookingResponse) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{19}
}

type JoinPublicWaitlistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationId     string `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	ServiceId      string `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	SlotId         string `protobuf:"bytes,3,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	GuestName      string `protobuf:"bytes,4,opt,name=guest_name,json=guestName,proto3" json:"guest_name,omitempty"`
	GuestEmail     string `protobuf:"bytes,5,opt,name=guest_email,json=guestEmail,proto3" json:"guest_email,omitempty"`
	GuestPhone     string `protobuf:"bytes,6,opt,name=guest_phone,json=guestPhone,proto3" json:"guest_phone,omitempty"`
	PractitionerId string `protobuf:"bytes,7,opt,name=practitioner_id,json=practitionerId,proto3" json:"practitioner_id,omitempty"`
	PreferredDate  string `protobuf:"bytes,8,opt,name=preferred_date,json=preferredDate,proto3" json:"preferred_date,omitempty"`
}

func (x *JoinPublicWaitlistRequest) Reset() {
	*x = JoinPublicWaitlistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinPublicWaitlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPublicWaitlistRequest) ProtoMessage() {}

func (x *JoinPublicWaitlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPublicWaitlistRequest.ProtoReflect.Descriptor instead.
func (*JoinPublicWaitlistRequest) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{20}
}

func (x *JoinPublicWaitlistRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *JoinPublicWaitlistRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *JoinPublicWaitlistRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *JoinPublicWaitlistRequest) GetGuestName() string {
	if x != nil {
		return x.GuestName
	}
	return ""
}

func (x *JoinPublicWaitlistRequest) GetGuestEmail() string {
	if x != nil {
		return x.GuestEmail
	}
	return ""
}

func (x *JoinPublicWaitlistRequest) GetGuestPhone() string {
	if x != nil {
		return x.GuestPhone
	}
	return ""
}

func (x *JoinPublicWaitlistRequest) GetPractitionerId() string {
	if x != nil {
		return x.PractitionerId
	}
	return ""
}

func (x *JoinPublicWaitlistRequest) GetPreferredDate() string {
	if x != nil {
		return x.PreferredDate
	}
	return ""
}

type JoinPublicWaitlistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WaitlistEntryId string `protobuf:"bytes,1,opt,name=waitlist_entry_id,json=waitlistEntryId,proto3" json:"waitlist_entry_id,omitempty"`
	Status          string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PositionHint    int32  `protobuf:"varint,3,opt,name=position_hint,json=positionHint,proto3" json:"position_hint,omitempty"`
}

func (x *JoinPublicWaitlistResponse) Reset() {
	*x = JoinPublicWaitlistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_public_booking_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinPublicWaitlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPublicWaitlistResponse) ProtoMessage() {}

func (x *JoinPublicWaitlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_public_booking_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPublicWaitlistResponse.ProtoReflect.Descriptor instead.
func (*JoinPublicWaitlistResponse) Descriptor() ([]byte, []int) {
	return file_rpc_public_booking_proto_rawDescGZIP(), []int{21}
}

func (x *JoinPublicWaitlistResponse) GetWaitlistEntryId() string {
	if x != nil {
		return x.WaitlistEntryId
	}
	return ""
}

func (x *JoinPublicWaitlistResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JoinPublicWaitlistResponse) GetPositionHint() int32 {
	if x != nil {
		return x.PositionHint
	}
	return 0
}

var File_rpc_public_booking_proto protoreflect.FileDescriptor

var file_rpc_public_booking_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xae,
	0x01, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x43, 0x0a, 0x1e, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x68,
	0x6f, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x1b, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x22,
	0xad, 0x01, 0x0a, 0x12, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x43, 0x0a, 0x1e, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x68,
	0x6f, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x1b, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x22,
	0x1c, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a,
	0x1b, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xf9, 0x01, 0x0a, 0x12, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73,
	0x12, 0x2a, 0x0a, 0x11, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x5f,
	0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x4d, 0x69, 0x6e, 0x6f, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x4c, 0x0a, 0x23, 0x63, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x69, 0x6e, 0x5f, 0x68, 0x6f, 0x75,
	0x72, 0x73, 0x5f, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x1f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x42, 0x65, 0x66, 0x6f, 0x72,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x22, 0x60, 0x0a, 0x17, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x53, 0x6c, 0x6f, 0x74, 0x73, 0x50, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x0f, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0xaa, 0x03, 0x0a, 0x0f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x07,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f,
	0x0a, 0x0c, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x53, 0x6c, 0x6f, 0x74, 0x73, 0x50, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65,
	0x72, 0x52, 0x0c, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x12,
	0x27, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x41, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x2f, 0x0a, 0x13, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x69,
	0x73, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x69, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6f, 0x6f, 0x6b,
	0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x62, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x73, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x4c, 0x65, 0x66, 0x74, 0x22, 0xbc, 0x02, 0x0a,
	0x16, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x6c, 0x6f, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x6f, 0x6e, 0x6c, 0x79, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0xf1, 0x01, 0x0a, 0x17,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22,
	0x39, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x18, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x50, 0x72, 0x61, 0x63, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a,
	0x10, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6c, 0x75, 0x67, 0x22, 0xe4, 0x01, 0x0a, 0x1e,
	0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x0d, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x50, 0x72, 0x61, 0x63,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x52, 0x0d, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x72, 0x6f,
	0x6f, 0x6d, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x6c, 0x6f, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f,
	0x74, 0x73, 0x22, 0xd8, 0x01, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x67,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x67, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x67,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x67, 0x75, 0x65, 0x73, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x67, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x84, 0x02,
	0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x67, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x67, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x67, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x67, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x27,
	0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x7a, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x83, 0x01, 0x0a, 0x1a, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xa5, 0x02, 0x0a, 0x19, 0x4a, 0x6f, 0x69, 0x6e, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x57, 0x61, 0x69, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x67, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x67,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x67, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1f, 0x0a, 0x0b,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x67, 0x75, 0x65, 0x73, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x72, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x85, 0x01,
	0x0a, 0x1a, 0x4a, 0x6f, 0x69, 0x6e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x57, 0x61, 0x69, 0x74,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x11,
	0x77, 0x61, 0x69, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x77, 0x61, 0x69, 0x74, 0x6c, 0x69, 0x73,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x69, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x69, 0x6e, 0x74, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x73, 0x68, 0x6d, 0x6f, 0x72, 0x65, 0x2f, 0x79, 0x74, 0x74,
	0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_public_booking_proto_rawDescOnce sync.Once
	file_rpc_public_booking_proto_rawDescData = file_rpc_public_booking_proto_rawDesc
)

func file_rpc_public_booking_proto_rawDescGZIP() []byte {
	file_rpc_public_booking_proto_rawDescOnce.Do(func() {
		file_rpc_public_booking_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_public_booking_proto_rawDescData)
	})
	return file_rpc_public_booking_proto_rawDescData
}

var file_rpc_public_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_rpc_public_booking_proto_goTypes = []interface{}{
	(*PublicSlotsLocation)(nil),            // 0: pb.PublicSlotsLocation
	(*PublicLocationItem)(nil),             // 1: pb.PublicLocationItem
	(*ListPublicLocationsRequest)(nil),     // 2: pb.ListPublicLocationsRequest
	(*ListPublicLocationsResponse)(nil),    // 3: pb.ListPublicLocationsResponse
	(*PublicSlotsService)(nil),             // 4: pb.PublicSlotsService
	(*PublicSlotsPractitioner)(nil),        // 5: pb.PublicSlotsPractitioner
	(*PublicSlotsRoom)(nil),                // 6: pb.PublicSlotsRoom
	(*PublicSlotsItem)(nil),                // 7: pb.PublicSlotsItem
	(*ListPublicSlotsRequest)(nil),         // 8: pb.ListPublicSlotsRequest
	(*ListPublicSlotsResponse)(nil),        // 9: pb.ListPublicSlotsResponse
	(*PublicFilterService)(nil),            // 10: pb.PublicFilterService
	(*PublicFilterPractitioner)(nil),       // 11: pb.PublicFilterPractitioner
	(*PublicFilterRoom)(nil),               // 12: pb.PublicFilterRoom
	(*GetPublicFilterOptionsRequest)(nil),  // 13: pb.GetPublicFilterOptionsRequest
	(*GetPublicFilterOptionsResponse)(nil), // 14: pb.GetPublicFilterOptionsResponse
	(*CreatePublicBookingRequest)(nil),     // 15: pb.CreatePublicBookingRequest
	(*CreatePublicBookingBooking)(nil),     // 16: pb.CreatePublicBookingBooking
	(*CreatePublicBookingResponse)(nil),    // 17: pb.CreatePublicBookingResponse
	(*CancelPublicBookingRequest)(nil),     // 18: pb.CancelPublicBookingRequest
	(*CancelPublicBookingResponse)(nil),    // 19: pb.CancelPublicBookingResponse
	(*JoinPublicWaitlistRequest)(nil),      // 20: pb.JoinPublicWaitlistRequest
	(*JoinPublicWaitlistResponse)(nil),     // 21: pb.JoinPublicWaitlistResponse
}
var file_rpc_public_booking_proto_depIdxs = []int32{
	1,  // 0: pb.ListPublicLocationsResponse.items:type_name -> pb.PublicLocationItem
	4,  // 1: pb.PublicSlotsItem.service:type_name -> pb.PublicSlotsService
	5,  // 2: pb.PublicSlotsItem.practitioner:type_name -> pb.PublicSlotsPractitioner
	6,  // 3: pb.PublicSlotsItem.room:type_name -> pb.PublicSlotsRoom
	0,  // 4: pb.ListPublicSlotsResponse.location:type_name -> pb.PublicSlotsLocation
	7,  // 5: pb.ListPublicSlotsResponse.items:type_name -> pb.PublicSlotsItem
	10, // 6: pb.GetPublicFilterOptionsResponse.services:type_name -> pb.PublicFilterService
	11, // 7: pb.GetPublicFilterOptionsResponse.practitioners:type_name -> pb.PublicFilterPractitioner
	12, // 8: pb.GetPublicFilterOptionsResponse.rooms:type_name -> pb.PublicFilterRoom
	16, // 9: pb.CreatePublicBookingResponse.booking:type_name -> pb.CreatePublicBookingBooking
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_rpc_public_booking_proto_init() }
func file_rpc_public_booking_proto_init() {
	if File_rpc_public_booking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_public_booking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicSlotsLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicLocationItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPublicLocationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPublicLocationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicSlotsService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicSlotsPractitioner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicSlotsRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicSlotsItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPublicSlotsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPublicSlotsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicFilterService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicFilterPractitioner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicFilterRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPublicFilterOptionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPublicFilterOptionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePublicBookingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePublicBookingBooking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePublicBookingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelPublicBookingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelPublicBookingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinPublicWaitlistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_public_booking_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinPublicWaitlistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_public_booking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_public_booking_proto_goTypes,
		DependencyIndexes: file_rpc_public_booking_proto_depIdxs,
		MessageInfos:      file_rpc_public_booking_proto_msgTypes,
	}.Build()
	File_rpc_public_booking_proto = out.File
	file_rpc_public_booking_proto_rawDesc = nil
	file_rpc_public_booking_proto_goTypes = nil
	file_rpc_public_booking_proto_depIdxs = nil
}
