// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.28.1
// source: rpc_host_booking.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostLocationItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                            string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name                            string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	BookingRequiresHostApproval     bool   `protobuf:"varint,4,opt,name=booking_requires_host_approval,json=bookingRequiresHostApproval,proto3" json:"booking_requires_host_approval,omitempty"`
	CancellationMinHoursBeforeStart int32  `protobuf:"varint,5,opt,name=cancellation_min_hours_before_start,json=cancellationMinHoursBeforeStart,proto3" json:"cancellation_min_hours_before_start,omitempty"`
	OwnerUsername                   string `protobuf:"bytes,6,opt,name=owner_username,json=ownerUsername,proto3" json:"owner_username,omitempty"`
	Timezone                        string `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	IsActive                        bool   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *HostLocationItem) Reset() {
	*x = HostLocationItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostLocationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostLocationItem) ProtoMessage() {}

func (x *HostLocationItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostLocationItem.ProtoReflect.Descriptor instead.
func (*HostLocationItem) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{0}
}

func (x *HostLocationItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HostLocationItem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *HostLocationItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostLocationItem) GetBookingRequiresHostApproval() bool {
	if x != nil {
		return x.BookingRequiresHostApproval
	}
	return false
}

func (x *HostLocationItem) GetCancellationMinHoursBeforeStart() int32 {
	if x != nil {
		return x.CancellationMinHoursBeforeStart
	}
	return 0
}

func (x *HostLocationItem) GetOwnerUsername() string {
	if x != nil {
		return x.OwnerUsername
	}
	return ""
}

func (x *HostLocationItem) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *HostLocationItem) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ListHostLocationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListHostLocationsRequest) Reset() {
	*x = ListHostLocationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHostLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostLocationsRequest) ProtoMessage() {}

func (x *ListHostLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostLocationsRequest.ProtoReflect.Descriptor instead.
func (*ListHostLocationsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{1}
}

type ListHostLocationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*HostLocationItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListHostLocationsResponse) Reset() {
	*x = ListHostLocationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHostLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostLocationsResponse) ProtoMessage() {}

func (x *ListHostLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostLocationsResponse.ProtoReflect.Descriptor instead.
func (*ListHostLocationsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{2}
}

func (x *ListHostLocationsResponse) GetItems() []*HostLocationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateHostLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug     string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Timezone string `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	IsActive *bool  `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
}

func (x *CreateHostLocationRequest) Reset() {
	*x = CreateHostLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHostLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostLocationRequest) ProtoMessage() {}

func (x *CreateHostLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostLocationRequest.ProtoReflect.Descriptor instead.
func (*CreateHostLocationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{3}
}

func (x *CreateHostLocationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHostLocationRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateHostLocationRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CreateHostLocationRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type CreateHostLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *HostLocationItem `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *CreateHostLocationResponse) Reset() {
	*x = CreateHostLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHostLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostLocationResponse) ProtoMessage() {}

func (x *CreateHostLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostLocationResponse.ProtoReflect.Descriptor instead.
func (*CreateHostLocationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{4}
}

func (x *CreateHostLocationResponse) GetLocation() *HostLocationItem {
	if x != nil {
		return x.Location
	}
	return nil
}

type GetHostLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationId string `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
}

func (x *GetHostLocationRequest) Reset() {
	*x = GetHostLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostLocationRequest) ProtoMessage() {}

func (x *GetHostLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostLocationRequest.ProtoReflect.Descriptor instead.
func (*GetHostLocationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{5}
}

func (x *GetHostLocationRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

type GetHostLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *HostLocationItem `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *GetHostLocationResponse) Reset() {
	*x = GetHostLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostLocationResponse) ProtoMessage() {}

func (x *GetHostLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostLocationResponse.ProtoReflect.Descriptor instead.
func (*GetHostLocationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{6}
}

func (x *GetHostLocationResponse) GetLocation() *HostLocationItem {
	if x != nil {
		return x.Location
	}
	return nil
}

type GetHostLocationBySlugRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationSlug string `protobuf:"bytes,1,opt,name=location_slug,json=locationSlug,proto3" json:"location_slug,omitempty"`
}

func (x *GetHostLocationBySlugRequest) Reset() {
	*x = GetHostLocationBySlugRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostLocationBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostLocationBySlugRequest) ProtoMessage() {}

func (x *GetHostLocationBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostLocationBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetHostLocationBySlugRequest) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{7}
}

func (x *GetHostLocationBySlugRequest) GetLocationSlug() string {
	if x != nil {
		return x.LocationSlug
	}
	return ""
}

type GetHostLocationBySlugResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *HostLocationItem `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *GetHostLocationBySlugResponse) Reset() {
	*x = GetHostLocationBySlugResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostLocationBySlugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostLocationBySlugResponse) ProtoMessage() {}

func (x *GetHostLocationBySlugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostLocationBySlugResponse.ProtoReflect.Descriptor instead.
func (*GetHostLocationBySlugResponse) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{8}
}

func (x *GetHostLocationBySlugResponse) GetLocation() *HostLocationItem {
	if x != nil {
		return x.Location
	}
	return nil
}

type UpdateHostLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationSlug                string  `protobuf:"bytes,1,opt,name=location_slug,json=locationSlug,proto3" json:"location_slug,omitempty"`
	Name                        *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Slug                        *string `protobuf:"bytes,3,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	Timezone                    *string `protobuf:"bytes,4,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	IsActive                    *bool   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	BookingRequiresHostApproval *bool   `protobuf:"varint,6,opt,name=booking_requires_host_approval,json=bookingRequiresHostApproval,proto3,oneof" json:"booking_requires_host_approval,omitempty"`
}

func (x *UpdateHostLocationRequest) Reset() {
	*x = UpdateHostLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHostLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostLocationRequest) ProtoMessage() {}

func (x *UpdateHostLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateHostLocationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateHostLocationRequest) GetLocationSlug() string {
	if x != nil {
		return x.LocationSlug
	}
	return ""
}

func (x *UpdateHostLocationRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateHostLocationRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *UpdateHostLocationRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *UpdateHostLocationRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *UpdateHostLocationRequest) GetBookingRequiresHostApproval() bool {
	if x != nil && x.BookingRequiresHostApproval != nil {
		return *x.BookingRequiresHostApproval
	}
	return false
}

type UpdateHostLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *HostLocationItem `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *UpdateHostLocationResponse) Reset() {
	*x = UpdateHostLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHostLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostLocationResponse) ProtoMessage() {}

func (x *UpdateHostLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateHostLocationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateHostLocationResponse) GetLocation() *HostLocationItem {
	if x != nil {
		return x.Location
	}
	return nil
}

type HostBookingSlotSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotId           string `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	ServiceName      string `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	PractitionerName string `protobuf:"bytes,3,opt,name=practitioner_name,json=practitionerName,proto3" json:"practitioner_name,omitempty"`
	RoomName         string `protobuf:"bytes,4,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	StartAt          string `protobuf:"bytes,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt            string `protobuf:"bytes,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
}

func (x *HostBookingSlotSummary) Reset() {
	*x = HostBookingSlotSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostBookingSlotSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostBookingSlotSummary) ProtoMessage() {}

func (x *HostBookingSlotSummary) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostBookingSlotSummary.ProtoReflect.Descriptor instead.
func (*HostBookingSlotSummary) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{11}
}

func (x *HostBookingSlotSummary) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *HostBookingSlotSummary) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HostBookingSlotSummary) GetPractitionerName() string {
	if x != nil {
		return x.PractitionerName
	}
	return ""
}

func (x *HostBookingSlotSummary) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *HostBookingSlotSummary) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *HostBookingSlotSummary) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

type HostBookingListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingId    string                  `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Status       string                  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BookedAt     string                  `protobuf:"bytes,3,opt,name=booked_at,json=bookedAt,proto3" json:"booked_at,omitempty"`
	GuestName    string                  `protobuf:"bytes,4,opt,name=guest_name,json=guestName,proto3" json:"guest_name,omitempty"`
	GuestEmail   string                  `protobuf:"bytes,5,opt,name=guest_email,json=guestEmail,proto3" json:"guest_email,omitempty"`
	GuestPhone   string                  `protobuf:"bytes,6,opt,name=guest_phone,json=guestPhone,proto3" json:"guest_phone,omitempty"`
	Slot         *HostBookingSlotSummary `protobuf:"bytes,7,opt,name=slot,proto3" json:"slot,omitempty"`
	CancelReason string                  `protobuf:"bytes,8,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
}

func (x *HostBookingListItem) Reset() {
	*x = HostBookingListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostBookingListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostBookingListItem) ProtoMessage() {}

func (x *HostBookingListItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostBookingListItem.ProtoReflect.Descriptor instead.
func (*HostBookingListItem) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{12}
}

func (x *HostBookingListItem) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *HostBookingListItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HostBookingListItem) GetBookedAt() string {
	if x != nil {
		return x.BookedAt
	}
	return ""
}

func (x *HostBookingListItem) GetGuestName() string {
	if x != nil {
		return x.GuestName
	}
	return ""
}

func (x *HostBookingListItem) GetGuestEmail() string {
	if x != nil {
		return x.GuestEmail
	}
	return ""
}

func (x *HostBookingListItem) GetGuestPhone() string {
	if x != nil {
		return x.GuestPhone
	}
	return ""
}

func (x *HostBookingListItem) GetSlot() *HostBookingSlotSummary {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *HostBookingListItem) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

type ListHostLocationBookingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationSlug string `protobuf:"bytes,1,opt,name=location_slug,json=locationSlug,proto3" json:"location_slug,omitempty"`
	Status       string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FromDate     string `protobuf:"bytes,3,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate       string `protobuf:"bytes,4,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	Limit        int32  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset       int32  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListHostLocationBookingsRequest) Reset() {
	*x = ListHostLocationBookingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHostLocationBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostLocationBookingsRequest) ProtoMessage() {}

func (x *ListHostLocationBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostLocationBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListHostLocationBookingsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{13}
}

func (x *ListHostLocationBookingsRequest) GetLocationSlug() string {
	if x != nil {
		return x.LocationSlug
	}
	return ""
}

func (x *ListHostLocationBookingsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListHostLocationBookingsRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *ListHostLocationBookingsRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *ListHostLocationBookingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListHostLocationBookingsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListHostLocationBookingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items      []*HostBookingListItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Limit      int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset     int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListHostLocationBookingsResponse) Reset() {
	*x = ListHostLocationBookingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHostLocationBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostLocationBookingsResponse) ProtoMessage() {}

func (x *ListHostLocationBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostLocationBookingsResponse.ProtoReflect.Descriptor instead.
func (*ListHostLocationBookingsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{14}
}

func (x *ListHostLocationBookingsResponse) GetItems() []*HostBookingListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListHostLocationBookingsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListHostLocationBookingsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListHostLocationBookingsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type HostBookingDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LocationId     string `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	SlotId         string `protobuf:"bytes,3,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Status         string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	GuestName      string `protobuf:"bytes,5,opt,name=guest_name,json=guestName,proto3" json:"guest_name,omitempty"`
	GuestEmail     string `protobuf:"bytes,6,opt,name=guest_email,json=guestEmail,proto3" json:"guest_email,omitempty"`
	ClientUsername string `protobuf:"bytes,7,opt,name=client_username,json=clientUsername,proto3" json:"client_username,omitempty"`
	BookedAt       string `protobuf:"bytes,8,opt,name=booked_at,json=bookedAt,proto3" json:"booked_at,omitempty"`
}

func (x *HostBookingDetail) Reset() {
	*x = HostBookingDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostBookingDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostBookingDetail) ProtoMessage() {}

func (x *HostBookingDetail) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostBookingDetail.ProtoReflect.Descriptor instead.
func (*HostBookingDetail) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{15}
}

func (x *HostBookingDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HostBookingDetail) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *HostBookingDetail) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *HostBookingDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HostBookingDetail) GetGuestName() string {
	if x != nil {
		return x.GuestName
	}
	return ""
}

func (x *HostBookingDetail) GetGuestEmail() string {
	if x != nil {
		return x.GuestEmail
	}
	return ""
}

func (x *HostBookingDetail) GetClientUsername() string {
	if x != nil {
		return x.ClientUsername
	}
	return ""
}

func (x *HostBookingDetail) GetBookedAt() string {
	if x != nil {
		return x.BookedAt
	}
	return ""
}

type HostApproveBookingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingId string `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
}

func (x *HostApproveBookingRequest) Reset() {
	*x = HostApproveBookingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostApproveBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostApproveBookingRequest) ProtoMessage() {}

func (x *HostApproveBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostApproveBookingRequest.ProtoReflect.Descriptor instead.
func (*HostApproveBookingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{16}
}

func (x *HostApproveBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type HostApproveBookingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Booking *HostBookingDetail `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
}

func (x *HostApproveBookingResponse) Reset() {
	*x = HostApproveBookingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostApproveBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostApproveBookingResponse) ProtoMessage() {}

func (x *HostApproveBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostApproveBookingResponse.ProtoReflect.Descriptor instead.
func (*HostApproveBookingResponse) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{17}
}

func (x *HostApproveBookingResponse) GetBooking() *HostBookingDetail {
	if x != nil {
		return x.Booking
	}
	return nil
}

type HostRejectBookingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingId    string `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	CancelReason string `protobuf:"bytes,2,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
}

func (x *HostRejectBookingRequest) Reset() {
	*x = HostRejectBookingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostRejectBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostRejectBookingRequest) ProtoMessage() {}

func (x *HostRejectBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostRejectBookingRequest.ProtoReflect.Descriptor instead.
func (*HostRejectBookingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{18}
}

func (x *HostRejectBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *HostRejectBookingRequest) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

type HostRejectBookingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HostRejectBookingResponse) Reset() {
	*x = HostRejectBookingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostRejectBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostRejectBookingResponse) ProtoMessage() {}

func (x *HostRejectBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostRejectBookingResponse.ProtoReflect.Descriptor instead.
func (*HostRejectBookingResponse) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{19}
}

type HostCancelBookingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingId    string `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	CancelReason string `protobuf:"bytes,2,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
}

func (x *HostCancelBookingRequest) Reset() {
	*x = HostCancelBookingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostCancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCancelBookingRequest) ProtoMessage() {}

func (x *HostCancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCancelBookingRequest.ProtoReflect.Descriptor instead.
func (*HostCancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{20}
}

func (x *HostCancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *HostCancelBookingRequest) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

type HostCancelBookingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HostCancelBookingResponse) Reset() {
	*x = HostCancelBookingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_booking_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostCancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCancelBookingResponse) ProtoMessage() {}

func (x *HostCancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_booking_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCancelBookingResponse.ProtoReflect.Descriptor instead.
func (*HostCancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_rpc_host_booking_proto_rawDescGZIP(), []int{21}
}

var File_rpc_host_booking_proto protoreflect.FileDescriptor

var file_rpc_host_booking_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x70, 0x63, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xbd, 0x02, 0x0a,
	0x10, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x43, 0x0a, 0x1e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x68, 0x6f,
	0x73, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x1b, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x12, 0x4c,
	0x0a, 0x23, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d,
	0x69, 0x6e, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x5f, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x5f,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x1f, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x48, 0x6f, 0x75, 0x72,
	0x73, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x0e,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x1a, 0x0a, 0x18,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74,
	0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x8f, 0x01, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a,
	0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a,
	0x6f, 0x6e, 0x65, 0x12, 0x20, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x22, 0x4e, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73,
	0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x30, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x39, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x4b,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62,
	0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x43, 0x0a, 0x1c, 0x47,
	0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79,
	0x53, 0x6c, 0x75, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6c, 0x75, 0x67,
	0x22, 0x51, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x79, 0x53, 0x6c, 0x75, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x30, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0xcf, 0x02, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f,
	0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x6c,
	0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x17, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x04, 0x73, 0x6c, 0x75, 0x67, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65,
	0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x08, 0x74, 0x69,
	0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x69, 0x73, 0x5f,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x03, 0x52, 0x08,
	0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x88, 0x01, 0x01, 0x12, 0x48, 0x0a, 0x1e, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x5f,
	0x68, 0x6f, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x04, 0x52, 0x1b, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x61, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x7a, 0x6f, 0x6e, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x42, 0x21, 0x0a, 0x1f, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x61, 0x6c, 0x22, 0x4e, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48,
	0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xd0, 0x01, 0x0a, 0x16, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x11,
	0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x22, 0x9f, 0x02, 0x0a, 0x13, 0x48, 0x6f, 0x73,
	0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x75, 0x65, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x75, 0x65, 0x73, 0x74, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52,
	0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xc2, 0x01, 0x0a, 0x1f, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x6c, 0x75, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x72, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22,
	0xa0, 0x01, 0x0a, 0x20, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x22, 0xfb, 0x01, 0x0a, 0x11, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x3a, 0x0a, 0x19, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x42,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x1a,
	0x48, 0x6f, 0x73, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62,
	0x2e, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x22, 0x5e, 0x0a, 0x18, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x1b, 0x0a, 0x19, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5e, 0x0a, 0x18, 0x48, 0x6f, 0x73, 0x74,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x1b, 0x0a, 0x19, 0x48, 0x6f, 0x73, 0x74,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x73, 0x68, 0x6d, 0x6f, 0x72, 0x65, 0x2f, 0x79, 0x74, 0x74,
	0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_host_booking_proto_rawDescOnce sync.Once
	file_rpc_host_booking_proto_rawDescData = file_rpc_host_booking_proto_rawDesc
)

func file_rpc_host_booking_proto_rawDescGZIP() []byte {
	file_rpc_host_booking_proto_rawDescOnce.Do(func() {
		file_rpc_host_booking_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_host_booking_proto_rawDescData)
	})
	return file_rpc_host_booking_proto_rawDescData
}

var file_rpc_host_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_rpc_host_booking_proto_goTypes = []interface{}{
	(*HostLocationItem)(nil),                 // 0: pb.HostLocationItem
	(*ListHostLocationsRequest)(nil),         // 1: pb.ListHostLocationsRequest
	(*ListHostLocationsResponse)(nil),        // 2: pb.ListHostLocationsResponse
	(*CreateHostLocationRequest)(nil),        // 3: pb.CreateHostLocationRequest
	(*CreateHostLocationResponse)(nil),       // 4: pb.CreateHostLocationResponse
	(*GetHostLocationRequest)(nil),           // 5: pb.GetHostLocationRequest
	(*GetHostLocationResponse)(nil),          // 6: pb.GetHostLocationResponse
	(*GetHostLocationBySlugRequest)(nil),     // 7: pb.GetHostLocationBySlugRequest
	(*GetHostLocationBySlugResponse)(nil),    // 8: pb.GetHostLocationBySlugResponse
	(*UpdateHostLocationRequest)(nil),        // 9: pb.UpdateHostLocationRequest
	(*UpdateHostLocationResponse)(nil),       // 10: pb.UpdateHostLocationResponse
	(*HostBookingSlotSummary)(nil),           // 11: pb.HostBookingSlotSummary
	(*HostBookingListItem)(nil),              // 12: pb.HostBookingListItem
	(*ListHostLocationBookingsRequest)(nil),  // 13: pb.ListHostLocationBookingsRequest
	(*ListHostLocationBookingsResponse)(nil), // 14: pb.ListHostLocationBookingsResponse
	(*HostBookingDetail)(nil),                // 15: pb.HostBookingDetail
	(*HostApproveBookingRequest)(nil),        // 16: pb.HostApproveBookingRequest
	(*HostApproveBookingResponse)(nil),       // 17: pb.HostApproveBookingResponse
	(*HostRejectBookingRequest)(nil),         // 18: pb.HostRejectBookingRequest
	(*HostRejectBookingResponse)(nil),        // 19: pb.HostRejectBookingResponse
	(*HostCancelBookingRequest)(nil),         // 20: pb.HostCancelBookingRequest
	(*HostCancelBookingResponse)(nil),        // 21: pb.HostCancelBookingResponse
}
var file_rpc_host_booking_proto_depIdxs = []int32{
	0,  // 0: pb.ListHostLocationsResponse.items:type_name -> pb.HostLocationItem
	0,  // 1: pb.CreateHostLocationResponse.location:type_name -> pb.HostLocationItem
	0,  // 2: pb.GetHostLocationResponse.location:type_name -> pb.HostLocationItem
	0,  // 3: pb.GetHostLocationBySlugResponse.location:type_name -> pb.HostLocationItem
	0,  // 4: pb.UpdateHostLocationResponse.location:type_name -> pb.HostLocationItem
	11, // 5: pb.HostBookingListItem.slot:type_name -> pb.HostBookingSlotSummary
	12, // 6: pb.ListHostLocationBookingsResponse.items:type_name -> pb.HostBookingListItem
	15, // 7: pb.HostApproveBookingResponse.booking:type_name -> pb.HostBookingDetail
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_rpc_host_booking_proto_init() }
func file_rpc_host_booking_proto_init() {
	if File_rpc_host_booking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_host_booking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostLocationItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHostLocationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHostLocationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHostLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHostLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostLocationBySlugRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostLocationBySlugResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHostLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHostLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostBookingSlotSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostBookingListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHostLocationBookingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHostLocationBookingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostBookingDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostApproveBookingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostApproveBookingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostRejectBookingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostRejectBookingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostCancelBookingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_booking_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostCancelBookingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rpc_host_booking_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_rpc_host_booking_proto_msgTypes[9].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_host_booking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_host_booking_proto_goTypes,
		DependencyIndexes: file_rpc_host_booking_proto_depIdxs,
		MessageInfos:      file_rpc_host_booking_proto_msgTypes,
	}.Build()
	File_rpc_host_booking_proto = out.File
	file_rpc_host_booking_proto_rawDesc = nil
	file_rpc_host_booking_proto_goTypes = nil
	file_rpc_host_booking_proto_depIdxs = nil
}
