// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.28.1
// source: rpc_host_ai.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostSlotAssistantPreviewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationSlug string `protobuf:"bytes,1,opt,name=location_slug,json=locationSlug,proto3" json:"location_slug,omitempty"`
	Prompt       string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *HostSlotAssistantPreviewRequest) Reset() {
	*x = HostSlotAssistantPreviewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_ai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostSlotAssistantPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSlotAssistantPreviewRequest) ProtoMessage() {}

func (x *HostSlotAssistantPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_ai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSlotAssistantPreviewRequest.ProtoReflect.Descriptor instead.
func (*HostSlotAssistantPreviewRequest) Descriptor() ([]byte, []int) {
	return file_rpc_host_ai_proto_rawDescGZIP(), []int{0}
}

func (x *HostSlotAssistantPreviewRequest) GetLocationSlug() string {
	if x != nil {
		return x.LocationSlug
	}
	return ""
}

func (x *HostSlotAssistantPreviewRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type HostSlotAssistantPlanOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartAt       string `protobuf:"bytes,1,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         string `protobuf:"bytes,2,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	ServiceName   string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ResourceLabel string `protobuf:"bytes,4,opt,name=resource_label,json=resourceLabel,proto3" json:"resource_label,omitempty"`
	// valid | warning | error
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Note   string `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *HostSlotAssistantPlanOperation) Reset() {
	*x = HostSlotAssistantPlanOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_ai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostSlotAssistantPlanOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSlotAssistantPlanOperation) ProtoMessage() {}

func (x *HostSlotAssistantPlanOperation) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_ai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSlotAssistantPlanOperation.ProtoReflect.Descriptor instead.
func (*HostSlotAssistantPlanOperation) Descriptor() ([]byte, []int) {
	return file_rpc_host_ai_proto_rawDescGZIP(), []int{1}
}

func (x *HostSlotAssistantPlanOperation) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *HostSlotAssistantPlanOperation) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *HostSlotAssistantPlanOperation) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HostSlotAssistantPlanOperation) GetResourceLabel() string {
	if x != nil {
		return x.ResourceLabel
	}
	return ""
}

func (x *HostSlotAssistantPlanOperation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HostSlotAssistantPlanOperation) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type HostSlotAssistantPreviewResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanId               string                            `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PlanOperations       []*HostSlotAssistantPlanOperation `protobuf:"bytes,2,rep,name=plan_operations,json=planOperations,proto3" json:"plan_operations,omitempty"`
	ValidationErrors     []string                          `protobuf:"bytes,3,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	RequiresConfirmation bool                              `protobuf:"varint,4,opt,name=requires_confirmation,json=requiresConfirmation,proto3" json:"requires_confirmation,omitempty"`
	Confidence           float64                           `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Model                string                            `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	TraceId              string                            `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Inclusive calendar bounds (YYYY-MM-DD) from the generated plan
	PlanDateFrom   string `protobuf:"bytes,8,opt,name=plan_date_from,json=planDateFrom,proto3" json:"plan_date_from,omitempty"`
	PlanDateTo     string `protobuf:"bytes,9,opt,name=plan_date_to,json=planDateTo,proto3" json:"plan_date_to,omitempty"`
	TotalSlotCount int32  `protobuf:"varint,10,opt,name=total_slot_count,json=totalSlotCount,proto3" json:"total_slot_count,omitempty"`
}

func (x *HostSlotAssistantPreviewResponse) Reset() {
	*x = HostSlotAssistantPreviewResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_ai_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostSlotAssistantPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSlotAssistantPreviewResponse) ProtoMessage() {}

func (x *HostSlotAssistantPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_ai_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSlotAssistantPreviewResponse.ProtoReflect.Descriptor instead.
func (*HostSlotAssistantPreviewResponse) Descriptor() ([]byte, []int) {
	return file_rpc_host_ai_proto_rawDescGZIP(), []int{2}
}

func (x *HostSlotAssistantPreviewResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *HostSlotAssistantPreviewResponse) GetPlanOperations() []*HostSlotAssistantPlanOperation {
	if x != nil {
		return x.PlanOperations
	}
	return nil
}

func (x *HostSlotAssistantPreviewResponse) GetValidationErrors() []string {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

func (x *HostSlotAssistantPreviewResponse) GetRequiresConfirmation() bool {
	if x != nil {
		return x.RequiresConfirmation
	}
	return false
}

func (x *HostSlotAssistantPreviewResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *HostSlotAssistantPreviewResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *HostSlotAssistantPreviewResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *HostSlotAssistantPreviewResponse) GetPlanDateFrom() string {
	if x != nil {
		return x.PlanDateFrom
	}
	return ""
}

func (x *HostSlotAssistantPreviewResponse) GetPlanDateTo() string {
	if x != nil {
		return x.PlanDateTo
	}
	return ""
}

func (x *HostSlotAssistantPreviewResponse) GetTotalSlotCount() int32 {
	if x != nil {
		return x.TotalSlotCount
	}
	return 0
}

type HostSlotAssistantPublishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationSlug   string `protobuf:"bytes,1,opt,name=location_slug,json=locationSlug,proto3" json:"location_slug,omitempty"`
	PlanId         string `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Confirmed      bool   `protobuf:"varint,3,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
}

func (x *HostSlotAssistantPublishRequest) Reset() {
	*x = HostSlotAssistantPublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_ai_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostSlotAssistantPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSlotAssistantPublishRequest) ProtoMessage() {}

func (x *HostSlotAssistantPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_ai_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSlotAssistantPublishRequest.ProtoReflect.Descriptor instead.
func (*HostSlotAssistantPublishRequest) Descriptor() ([]byte, []int) {
	return file_rpc_host_ai_proto_rawDescGZIP(), []int{3}
}

func (x *HostSlotAssistantPublishRequest) GetLocationSlug() string {
	if x != nil {
		return x.LocationSlug
	}
	return ""
}

func (x *HostSlotAssistantPublishRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *HostSlotAssistantPublishRequest) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *HostSlotAssistantPublishRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type HostSlotAssistantPublishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedCount int32                 `protobuf:"varint,1,opt,name=created_count,json=createdCount,proto3" json:"created_count,omitempty"`
	SkippedCount int32                 `protobuf:"varint,2,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"`
	Errors       []*HostSlotBatchError `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	TraceId      string                `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
}

func (x *HostSlotAssistantPublishResponse) Reset() {
	*x = HostSlotAssistantPublishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_host_ai_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostSlotAssistantPublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSlotAssistantPublishResponse) ProtoMessage() {}

func (x *HostSlotAssistantPublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_host_ai_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSlotAssistantPublishResponse.ProtoReflect.Descriptor instead.
func (*HostSlotAssistantPublishResponse) Descriptor() ([]byte, []int) {
	return file_rpc_host_ai_proto_rawDescGZIP(), []int{4}
}

func (x *HostSlotAssistantPublishResponse) GetCreatedCount() int32 {
	if x != nil {
		return x.CreatedCount
	}
	return 0
}

func (x *HostSlotAssistantPublishResponse) GetSkippedCount() int32 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

func (x *HostSlotAssistantPublishResponse) GetErrors() []*HostSlotBatchError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *HostSlotAssistantPublishResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_rpc_host_ai_proto protoreflect.FileDescriptor

var file_rpc_host_ai_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x70, 0x63, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x61, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x13, 0x72, 0x70, 0x63, 0x5f, 0x68, 0x6f, 0x73,
	0x74, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x1f,
	0x48, 0x6f, 0x73, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x41, 0x73, 0x73, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x74, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x23, 0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x6c, 0x75, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x6c, 0x75, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0xc8, 0x01, 0x0a,
	0x1e, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x41, 0x73, 0x73, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0xad, 0x03, 0x0a, 0x20, 0x48, 0x6f, 0x73, 0x74,
	0x53, 0x6c, 0x6f, 0x74, 0x41, 0x73, 0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x50, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x4b, 0x0a, 0x0f, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x41, 0x73, 0x73, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x6e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12,
	0x33, 0x0a, 0x15, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70,
	0x6c, 0x61, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x20, 0x0a, 0x0c, 0x70,
	0x6c, 0x61, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x12, 0x28, 0x0a,
	0x10, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x6c,
	0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xa6, 0x01, 0x0a, 0x1f, 0x48, 0x6f, 0x73, 0x74,
	0x53, 0x6c, 0x6f, 0x74, 0x41, 0x73, 0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6c, 0x75, 0x67,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x64, 0x65, 0x6d, 0x70,
	0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79,
	0x22, 0xb7, 0x01, 0x0a, 0x20, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x41, 0x73, 0x73,
	0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6b,
	0x69, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x73, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x2e, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12,
	0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x73, 0x68, 0x6d, 0x6f, 0x72,
	0x65, 0x2f, 0x79, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rpc_host_ai_proto_rawDescOnce sync.Once
	file_rpc_host_ai_proto_rawDescData = file_rpc_host_ai_proto_rawDesc
)

func file_rpc_host_ai_proto_rawDescGZIP() []byte {
	file_rpc_host_ai_proto_rawDescOnce.Do(func() {
		file_rpc_host_ai_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_host_ai_proto_rawDescData)
	})
	return file_rpc_host_ai_proto_rawDescData
}

var file_rpc_host_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpc_host_ai_proto_goTypes = []interface{}{
	(*HostSlotAssistantPreviewRequest)(nil),  // 0: pb.HostSlotAssistantPreviewRequest
	(*HostSlotAssistantPlanOperation)(nil),   // 1: pb.HostSlotAssistantPlanOperation
	(*HostSlotAssistantPreviewResponse)(nil), // 2: pb.HostSlotAssistantPreviewResponse
	(*HostSlotAssistantPublishRequest)(nil),  // 3: pb.HostSlotAssistantPublishRequest
	(*HostSlotAssistantPublishResponse)(nil), // 4: pb.HostSlotAssistantPublishResponse
	(*HostSlotBatchError)(nil),               // 5: pb.HostSlotBatchError
}
var file_rpc_host_ai_proto_depIdxs = []int32{
	1, // 0: pb.HostSlotAssistantPreviewResponse.plan_operations:type_name -> pb.HostSlotAssistantPlanOperation
	5, // 1: pb.HostSlotAssistantPublishResponse.errors:type_name -> pb.HostSlotBatchError
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_host_ai_proto_init() }
func file_rpc_host_ai_proto_init() {
	if File_rpc_host_ai_proto != nil {
		return
	}
	file_rpc_host_slot_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_host_ai_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostSlotAssistantPreviewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_ai_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostSlotAssistantPlanOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_ai_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostSlotAssistantPreviewResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_ai_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostSlotAssistantPublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_host_ai_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostSlotAssistantPublishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_host_ai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_host_ai_proto_goTypes,
		DependencyIndexes: file_rpc_host_ai_proto_depIdxs,
		MessageInfos:      file_rpc_host_ai_proto_msgTypes,
	}.Build()
	File_rpc_host_ai_proto = out.File
	file_rpc_host_ai_proto_rawDesc = nil
	file_rpc_host_ai_proto_goTypes = nil
	file_rpc_host_ai_proto_depIdxs = nil
}
